<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ComposantsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('composants')->delete();
        
        \DB::table('composants')->insert(array (
            0 => 
            array (
                'id' => 11,
                'reference' => 'ALN-361',
                'designation' => 'BARREAU RECTANGULAIRE',
                'slug' => 'aln-361-barreau-rectangulaire',
                'type_composant_id' => 1,
                'gamme_id' => NULL,
                'matiere' => NULL,
                'longueur_barre_mm' => NULL,
                'section_largeur_mm' => NULL,
                'section_hauteur_mm' => NULL,
                'epaisseur_paroi_mm' => NULL,
                'poids_lineaire_kg_m' => '0.489',
                'poids_lineaire_lbs_ft' => '0.329',
                'moment_inertie_cm4' => NULL,
                'perimetre_mm' => '114.20',
                'image_coupe' => NULL,
                'est_disponible' => 1,
                'created_at' => '2026-09-14 19:20:41',
                'updated_at' => '2026-09-15 19:20:11',
            ),
            1 => 
            array (
                'id' => 12,
                'reference' => 'ALN-362',
                'designation' => 'BARREAU OVAL',
                'slug' => 'aln-362-barreau-oval',
                'type_composant_id' => 1,
                'gamme_id' => NULL,
                'matiere' => NULL,
                'longueur_barre_mm' => NULL,
                'section_largeur_mm' => NULL,
                'section_hauteur_mm' => NULL,
                'epaisseur_paroi_mm' => NULL,
                'poids_lineaire_kg_m' => '0.395',
                'poids_lineaire_lbs_ft' => '0.265',
                'moment_inertie_cm4' => NULL,
                'perimetre_mm' => '118.72',
                'image_coupe' => NULL,
                'est_disponible' => 1,
                'created_at' => '2026-09-14 19:22:21',
                'updated_at' => '2026-09-15 19:20:11',
            ),
            2 => 
            array (
                'id' => 13,
                'reference' => 'ALN-937',
                'designation' => 'BARREAU CARRE',
                'slug' => 'aln-937-barreau-carre',
                'type_composant_id' => 1,
                'gamme_id' => NULL,
                'matiere' => NULL,
                'longueur_barre_mm' => NULL,
                'section_largeur_mm' => NULL,
                'section_hauteur_mm' => NULL,
                'epaisseur_paroi_mm' => NULL,
                'poids_lineaire_kg_m' => '0.427',
                'poids_lineaire_lbs_ft' => '0.287',
                'moment_inertie_cm4' => NULL,
                'perimetre_mm' => '87.66',
                'image_coupe' => NULL,
                'est_disponible' => 1,
                'created_at' => '2026-09-14 19:23:21',
                'updated_at' => '2026-09-15 19:20:11',
            ),
            3 => 
            array (
                'id' => 14,
                'reference' => 'ALN-1013',
                'designation' => 'BARREAU HEXAGONAL GRAND',
                'slug' => 'aln-1013-barreau-hexagonal-grand',
                'type_composant_id' => 1,
                'gamme_id' => NULL,
                'matiere' => NULL,
                'longueur_barre_mm' => NULL,
                'section_largeur_mm' => NULL,
                'section_hauteur_mm' => NULL,
                'epaisseur_paroi_mm' => NULL,
                'poids_lineaire_kg_m' => '0.498',
                'poids_lineaire_lbs_ft' => '0.335',
                'moment_inertie_cm4' => NULL,
                'perimetre_mm' => '131.99',
                'image_coupe' => NULL,
                'est_disponible' => 1,
                'created_at' => '2026-09-14 19:35:27',
                'updated_at' => '2026-09-15 19:20:11',
            ),
            4 => 
            array (
                'id' => 15,
                'reference' => 'ALN-1077',
                'designation' => 'BARREAU ROND',
                'slug' => 'aln-1077-barreau-rond',
                'type_composant_id' => 1,
                'gamme_id' => NULL,
                'matiere' => NULL,
                'longueur_barre_mm' => NULL,
                'section_largeur_mm' => NULL,
                'section_hauteur_mm' => NULL,
                'epaisseur_paroi_mm' => NULL,
                'poids_lineaire_kg_m' => '0.492',
                'poids_lineaire_lbs_ft' => '0.331',
                'moment_inertie_cm4' => NULL,
                'perimetre_mm' => '95.38',
                'image_coupe' => NULL,
                'est_disponible' => 1,
                'created_at' => '2026-09-14 19:36:19',
                'updated_at' => '2026-09-15 19:20:11',
            ),
            5 => 
            array (
                'id' => 16,
                'reference' => 'ALN-853',
                'designation' => 'SUPPORT BARREAU',
                'slug' => 'aln-853-support-barreau',
                'type_composant_id' => 1,
                'gamme_id' => NULL,
                'matiere' => NULL,
                'longueur_barre_mm' => NULL,
                'section_largeur_mm' => NULL,
                'section_hauteur_mm' => NULL,
                'epaisseur_paroi_mm' => NULL,
                'poids_lineaire_kg_m' => '0.243',
                'poids_lineaire_lbs_ft' => '0.163',
                'moment_inertie_cm4' => NULL,
                'perimetre_mm' => '103.20',
                'image_coupe' => NULL,
                'est_disponible' => 1,
                'created_at' => '2026-09-14 19:37:10',
                'updated_at' => '2026-09-15 19:20:11',
            ),
            6 => 
            array (
                'id' => 17,
                'reference' => 'ALN-876',
                'designation' => 'HORIZONTAL',
                'slug' => 'aln-876-horizontal',
                'type_composant_id' => 1,
                'gamme_id' => NULL,
                'matiere' => NULL,
                'longueur_barre_mm' => NULL,
                'section_largeur_mm' => NULL,
                'section_hauteur_mm' => NULL,
                'epaisseur_paroi_mm' => NULL,
                'poids_lineaire_kg_m' => '0.548',
                'poids_lineaire_lbs_ft' => '0.368',
                'moment_inertie_cm4' => NULL,
                'perimetre_mm' => '205.39',
                'image_coupe' => NULL,
                'est_disponible' => 1,
                'created_at' => '2026-09-14 19:38:27',
                'updated_at' => '2026-09-15 19:20:11',
            ),
            7 => 
            array (
                'id' => 18,
                'reference' => 'ALN-879',
                'designation' => 'CLIP',
                'slug' => 'aln-879-clip',
                'type_composant_id' => 1,
                'gamme_id' => NULL,
                'matiere' => NULL,
                'longueur_barre_mm' => NULL,
                'section_largeur_mm' => NULL,
                'section_hauteur_mm' => NULL,
                'epaisseur_paroi_mm' => NULL,
                'poids_lineaire_kg_m' => '0.385',
                'poids_lineaire_lbs_ft' => '0.259',
                'moment_inertie_cm4' => NULL,
                'perimetre_mm' => '150.01',
                'image_coupe' => NULL,
                'est_disponible' => 1,
                'created_at' => '2026-09-14 19:39:07',
                'updated_at' => '2026-09-15 19:20:11',
            ),
            8 => 
            array (
                'id' => 19,
                'reference' => 'ALN-878',
                'designation' => 'MAIN COURANTE',
                'slug' => 'aln-878-main-courante',
                'type_composant_id' => 1,
                'gamme_id' => NULL,
                'matiere' => NULL,
                'longueur_barre_mm' => NULL,
                'section_largeur_mm' => NULL,
                'section_hauteur_mm' => NULL,
                'epaisseur_paroi_mm' => NULL,
                'poids_lineaire_kg_m' => '0.740',
                'poids_lineaire_lbs_ft' => '0.497',
                'moment_inertie_cm4' => NULL,
                'perimetre_mm' => '291.08',
                'image_coupe' => NULL,
                'est_disponible' => 1,
                'created_at' => '2026-09-14 19:39:48',
                'updated_at' => '2026-09-15 19:20:11',
            ),
            9 => 
            array (
                'id' => 20,
                'reference' => 'ALN-877',
                'designation' => 'VERTICAL',
                'slug' => 'aln-877-vertical',
                'type_composant_id' => 1,
                'gamme_id' => NULL,
                'matiere' => NULL,
                'longueur_barre_mm' => NULL,
                'section_largeur_mm' => NULL,
                'section_hauteur_mm' => NULL,
                'epaisseur_paroi_mm' => NULL,
                'poids_lineaire_kg_m' => '0.820',
                'poids_lineaire_lbs_ft' => '0.551',
                'moment_inertie_cm4' => NULL,
                'perimetre_mm' => '253.59',
                'image_coupe' => NULL,
                'est_disponible' => 1,
                'created_at' => '2026-09-14 19:40:41',
                'updated_at' => '2026-09-15 19:20:11',
            ),
            10 => 
            array (
                'id' => 21,
                'reference' => 'ALN-1300',
                'designation' => 'BARREAU HEXAGONAL PETIT',
                'slug' => 'aln-1300-barreau-hexagonal-petit',
                'type_composant_id' => 1,
                'gamme_id' => NULL,
                'matiere' => NULL,
                'longueur_barre_mm' => NULL,
                'section_largeur_mm' => NULL,
                'section_hauteur_mm' => NULL,
                'epaisseur_paroi_mm' => NULL,
                'poids_lineaire_kg_m' => '0.285',
                'poids_lineaire_lbs_ft' => '0.192',
                'moment_inertie_cm4' => NULL,
                'perimetre_mm' => '77.64',
                'image_coupe' => NULL,
                'est_disponible' => 1,
                'created_at' => '2026-09-14 19:41:20',
                'updated_at' => '2026-09-15 19:20:11',
            ),
            11 => 
            array (
                'id' => 22,
                'reference' => 'ALN-1301',
                'designation' => 'BARREAU',
                'slug' => 'aln-1301-barreau',
                'type_composant_id' => 1,
                'gamme_id' => NULL,
                'matiere' => NULL,
                'longueur_barre_mm' => NULL,
                'section_largeur_mm' => NULL,
                'section_hauteur_mm' => NULL,
                'epaisseur_paroi_mm' => NULL,
                'poids_lineaire_kg_m' => '0.354',
                'poids_lineaire_lbs_ft' => '0.238',
                'moment_inertie_cm4' => NULL,
                'perimetre_mm' => '83.97',
                'image_coupe' => NULL,
                'est_disponible' => 1,
                'created_at' => '2026-09-14 19:41:51',
                'updated_at' => '2026-09-15 19:20:11',
            ),
            12 => 
            array (
                'id' => 23,
                'reference' => 'STC016',
                'designation' => 'ANCLAJES BARANDAS',
                'slug' => 'stc016-anclajes-barandas',
                'type_composant_id' => 1,
                'gamme_id' => NULL,
                'matiere' => NULL,
                'longueur_barre_mm' => NULL,
                'section_largeur_mm' => NULL,
                'section_hauteur_mm' => NULL,
                'epaisseur_paroi_mm' => NULL,
                'poids_lineaire_kg_m' => '4.708',
                'poids_lineaire_lbs_ft' => '3.164',
                'moment_inertie_cm4' => '11.86',
                'perimetre_mm' => '301.21',
                'image_coupe' => NULL,
                'est_disponible' => 1,
                'created_at' => '2026-09-15 18:37:38',
                'updated_at' => '2026-09-15 19:20:11',
            ),
            13 => 
            array (
                'id' => 25,
                'reference' => 'STC017',
                'designation' => 'ANCLAJES BARANDAS',
                'slug' => 'stc017-anclajes-barandas',
                'type_composant_id' => 1,
                'gamme_id' => NULL,
                'matiere' => NULL,
                'longueur_barre_mm' => NULL,
                'section_largeur_mm' => NULL,
                'section_hauteur_mm' => NULL,
                'epaisseur_paroi_mm' => NULL,
                'poids_lineaire_kg_m' => '3.673',
                'poids_lineaire_lbs_ft' => '2.468',
                'moment_inertie_cm4' => NULL,
                'perimetre_mm' => '244.93',
                'image_coupe' => NULL,
                'est_disponible' => 1,
                'created_at' => '2026-09-15 18:53:49',
                'updated_at' => '2026-09-15 19:20:11',
            ),
            14 => 
            array (
                'id' => 26,
                'reference' => 'STC018',
                'designation' => 'ANCLAJES BARANDAS',
                'slug' => 'stc018-anclajes-barandas',
                'type_composant_id' => 1,
                'gamme_id' => NULL,
                'matiere' => NULL,
                'longueur_barre_mm' => NULL,
                'section_largeur_mm' => NULL,
                'section_hauteur_mm' => NULL,
                'epaisseur_paroi_mm' => NULL,
                'poids_lineaire_kg_m' => '5.019',
                'poids_lineaire_lbs_ft' => '3.373',
                'moment_inertie_cm4' => NULL,
                'perimetre_mm' => '327.62',
                'image_coupe' => NULL,
                'est_disponible' => 1,
                'created_at' => '2026-09-15 18:55:41',
                'updated_at' => '2026-09-15 19:20:11',
            ),
            15 => 
            array (
                'id' => 27,
                'reference' => 'STC022',
                'designation' => 'ANCLAJES BARANDAS',
                'slug' => 'stc022-anclajes-barandas',
                'type_composant_id' => 1,
                'gamme_id' => NULL,
                'matiere' => NULL,
                'longueur_barre_mm' => NULL,
                'section_largeur_mm' => NULL,
                'section_hauteur_mm' => NULL,
                'epaisseur_paroi_mm' => NULL,
                'poids_lineaire_kg_m' => '1.101',
                'poids_lineaire_lbs_ft' => '0.740',
                'moment_inertie_cm4' => NULL,
                'perimetre_mm' => '116.57',
                'image_coupe' => NULL,
                'est_disponible' => 1,
                'created_at' => '2026-09-15 18:57:33',
                'updated_at' => '2026-09-15 19:20:11',
            ),
            16 => 
            array (
                'id' => 28,
                'reference' => 'STC023',
                'designation' => 'ANCLAJES BARANDAS',
                'slug' => 'stc023-anclajes-barandas',
                'type_composant_id' => 1,
                'gamme_id' => NULL,
                'matiere' => NULL,
                'longueur_barre_mm' => NULL,
                'section_largeur_mm' => NULL,
                'section_hauteur_mm' => NULL,
                'epaisseur_paroi_mm' => NULL,
                'poids_lineaire_kg_m' => '4.397',
                'poids_lineaire_lbs_ft' => '2.955',
                'moment_inertie_cm4' => NULL,
                'perimetre_mm' => '281.72',
                'image_coupe' => NULL,
                'est_disponible' => 1,
                'created_at' => '2026-09-15 18:59:22',
                'updated_at' => '2026-09-15 19:20:11',
            ),
            17 => 
            array (
                'id' => 29,
                'reference' => 'STC025',
                'designation' => 'ANCLAJES BARANDAS',
                'slug' => 'stc025-anclajes-barandas',
                'type_composant_id' => 1,
                'gamme_id' => NULL,
                'matiere' => NULL,
                'longueur_barre_mm' => NULL,
                'section_largeur_mm' => NULL,
                'section_hauteur_mm' => NULL,
                'epaisseur_paroi_mm' => NULL,
                'poids_lineaire_kg_m' => '0.700',
                'poids_lineaire_lbs_ft' => '0.470',
                'moment_inertie_cm4' => NULL,
                'perimetre_mm' => '238.23',
                'image_coupe' => NULL,
                'est_disponible' => 1,
                'created_at' => '2026-09-15 19:00:10',
                'updated_at' => '2026-09-15 19:20:11',
            ),
            18 => 
            array (
                'id' => 30,
                'reference' => 'STC020',
                'designation' => 'ANCLAJES BARANDAS',
                'slug' => 'stc020-anclajes-barandas',
                'type_composant_id' => 1,
                'gamme_id' => NULL,
                'matiere' => NULL,
                'longueur_barre_mm' => NULL,
                'section_largeur_mm' => NULL,
                'section_hauteur_mm' => NULL,
                'epaisseur_paroi_mm' => NULL,
                'poids_lineaire_kg_m' => '2.036',
                'poids_lineaire_lbs_ft' => '1.368',
                'moment_inertie_cm4' => NULL,
                'perimetre_mm' => '176.04',
                'image_coupe' => NULL,
                'est_disponible' => 1,
                'created_at' => '2026-09-15 19:01:05',
                'updated_at' => '2026-09-15 19:20:11',
            ),
            19 => 
            array (
                'id' => 31,
                'reference' => 'STC021',
                'designation' => 'ANCLAJES BARANDAS',
                'slug' => 'stc021-anclajes-barandas',
                'type_composant_id' => 1,
                'gamme_id' => NULL,
                'matiere' => NULL,
                'longueur_barre_mm' => NULL,
                'section_largeur_mm' => NULL,
                'section_hauteur_mm' => NULL,
                'epaisseur_paroi_mm' => NULL,
                'poids_lineaire_kg_m' => '1.010',
                'poids_lineaire_lbs_ft' => '0.679',
                'moment_inertie_cm4' => NULL,
                'perimetre_mm' => '144.67',
                'image_coupe' => NULL,
                'est_disponible' => 1,
                'created_at' => '2026-09-15 19:01:58',
                'updated_at' => '2026-09-15 19:20:11',
            ),
            20 => 
            array (
                'id' => 32,
                'reference' => 'STC024',
                'designation' => 'ANCLAJES BARANDAS',
                'slug' => 'stc024-anclajes-barandas',
                'type_composant_id' => 1,
                'gamme_id' => NULL,
                'matiere' => NULL,
                'longueur_barre_mm' => NULL,
                'section_largeur_mm' => NULL,
                'section_hauteur_mm' => NULL,
                'epaisseur_paroi_mm' => NULL,
                'poids_lineaire_kg_m' => '3.607',
                'poids_lineaire_lbs_ft' => '2.424',
                'moment_inertie_cm4' => NULL,
                'perimetre_mm' => '334.17',
                'image_coupe' => NULL,
                'est_disponible' => 1,
                'created_at' => '2026-09-15 19:02:53',
                'updated_at' => '2026-09-15 19:20:11',
            ),
        ));
        
        
    }
}