<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ComposantsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('composants')->delete();
        
        \DB::table('composants')->insert(array (
            0 => 
            array (
                'id' => 11,
                'reference' => 'ALN-361',
                'designation' => 'BARREAU RECTANGULAIRE',
                'slug' => 'aln-361-barreau-rectangulaire',
                'type_composant_id' => 1,
                'gamme_id' => NULL,
                'matiere' => NULL,
                'longueur_barre_mm' => NULL,
                'section_largeur_mm' => NULL,
                'section_hauteur_mm' => NULL,
                'epaisseur_paroi_mm' => NULL,
                'poids_lineaire_kg_m' => '0.489',
                'poids_lineaire_lbs_ft' => '0.329',
                'moment_inertie_cm4' => NULL,
                'perimetre_mm' => '114.20',
                'image_coupe' => NULL,
                'est_disponible' => 1,
                'created_at' => '2026-09-14 19:20:41',
                'updated_at' => '2026-09-15 19:20:11',
            ),
            1 => 
            array (
                'id' => 12,
                'reference' => 'ALN-362',
                'designation' => 'BARREAU OVAL',
                'slug' => 'aln-362-barreau-oval',
                'type_composant_id' => 1,
                'gamme_id' => NULL,
                'matiere' => NULL,
                'longueur_barre_mm' => NULL,
                'section_largeur_mm' => NULL,
                'section_hauteur_mm' => NULL,
                'epaisseur_paroi_mm' => NULL,
                'poids_lineaire_kg_m' => '0.395',
                'poids_lineaire_lbs_ft' => '0.265',
                'moment_inertie_cm4' => NULL,
                'perimetre_mm' => '118.72',
                'image_coupe' => NULL,
                'est_disponible' => 1,
                'created_at' => '2026-09-14 19:22:21',
                'updated_at' => '2026-09-15 19:20:11',
            ),
            2 => 
            array (
                'id' => 13,
                'reference' => 'ALN-937',
                'designation' => 'BARREAU CARRE',
                'slug' => 'aln-937-barreau-carre',
                'type_composant_id' => 1,
                'gamme_id' => NULL,
                'matiere' => NULL,
                'longueur_barre_mm' => NULL,
                'section_largeur_mm' => NULL,
                'section_hauteur_mm' => NULL,
                'epaisseur_paroi_mm' => NULL,
                'poids_lineaire_kg_m' => '0.427',
                'poids_lineaire_lbs_ft' => '0.287',
                'moment_inertie_cm4' => NULL,
                'perimetre_mm' => '87.66',
                'image_coupe' => NULL,
                'est_disponible' => 1,
                'created_at' => '2026-09-14 19:23:21',
                'updated_at' => '2026-09-15 19:20:11',
            ),
            3 => 
            array (
                'id' => 14,
                'reference' => 'ALN-1013',
                'designation' => 'BARREAU HEXAGONAL GRAND',
                'slug' => 'aln-1013-barreau-hexagonal-grand',
                'type_composant_id' => 1,
                'gamme_id' => NULL,
                'matiere' => NULL,
                'longueur_barre_mm' => NULL,
                'section_largeur_mm' => NULL,
                'section_hauteur_mm' => NULL,
                'epaisseur_paroi_mm' => NULL,
                'poids_lineaire_kg_m' => '0.498',
                'poids_lineaire_lbs_ft' => '0.335',
                'moment_inertie_cm4' => NULL,
                'perimetre_mm' => '131.99',
                'image_coupe' => NULL,
                'est_disponible' => 1,
                'created_at' => '2026-09-14 19:35:27',
                'updated_at' => '2026-09-15 19:20:11',
            ),
            4 => 
            array (
                'id' => 15,
                'reference' => 'ALN-1077',
                'designation' => 'BARREAU ROND',
                'slug' => 'aln-1077-barreau-rond',
                'type_composant_id' => 1,
                'gamme_id' => NULL,
                'matiere' => NULL,
                'longueur_barre_mm' => NULL,
                'section_largeur_mm' => NULL,
                'section_hauteur_mm' => NULL,
                'epaisseur_paroi_mm' => NULL,
                'poids_lineaire_kg_m' => '0.492',
                'poids_lineaire_lbs_ft' => '0.331',
                'moment_inertie_cm4' => NULL,
                'perimetre_mm' => '95.38',
                'image_coupe' => NULL,
                'est_disponible' => 1,
                'created_at' => '2026-09-14 19:36:19',
                'updated_at' => '2026-09-15 19:20:11',
            ),
            5 => 
            array (
                'id' => 16,
                'reference' => 'ALN-853',
                'designation' => 'SUPPORT BARREAU',
                'slug' => 'aln-853-support-barreau',
                'type_composant_id' => 1,
                'gamme_id' => NULL,
                'matiere' => NULL,
                'longueur_barre_mm' => NULL,
                'section_largeur_mm' => NULL,
                'section_hauteur_mm' => NULL,
                'epaisseur_paroi_mm' => NULL,
                'poids_lineaire_kg_m' => '0.243',
                'poids_lineaire_lbs_ft' => '0.163',
                'moment_inertie_cm4' => NULL,
                'perimetre_mm' => '103.20',
                'image_coupe' => NULL,
                'est_disponible' => 1,
                'created_at' => '2026-09-14 19:37:10',
                'updated_at' => '2026-09-15 19:20:11',
            ),
            6 => 
            array (
                'id' => 17,
                'reference' => 'ALN-876',
                'designation' => 'HORIZONTAL',
                'slug' => 'aln-876-horizontal',
                'type_composant_id' => 1,
                'gamme_id' => NULL,
                'matiere' => NULL,
                'longueur_barre_mm' => NULL,
                'section_largeur_mm' => NULL,
                'section_hauteur_mm' => NULL,
                'epaisseur_paroi_mm' => NULL,
                'poids_lineaire_kg_m' => '0.548',
                'poids_lineaire_lbs_ft' => '0.368',
                'moment_inertie_cm4' => NULL,
                'perimetre_mm' => '205.39',
                'image_coupe' => NULL,
                'est_disponible' => 1,
                'created_at' => '2026-09-14 19:38:27',
                'updated_at' => '2026-09-15 19:20:11',
            ),
            7 => 
            array (
                'id' => 18,
                'reference' => 'ALN-879',
                'designation' => 'CLIP',
                'slug' => 'aln-879-clip',
                'type_composant_id' => 1,
                'gamme_id' => NULL,
                'matiere' => NULL,
                'longueur_barre_mm' => NULL,
                'section_largeur_mm' => NULL,
                'section_hauteur_mm' => NULL,
                'epaisseur_paroi_mm' => NULL,
                'poids_lineaire_kg_m' => '0.385',
                'poids_lineaire_lbs_ft' => '0.259',
                'moment_inertie_cm4' => NULL,
                'perimetre_mm' => '150.01',
                'image_coupe' => NULL,
                'est_disponible' => 1,
                'created_at' => '2026-09-14 19:39:07',
                'updated_at' => '2026-09-15 19:20:11',
            ),
            8 => 
            array (
                'id' => 19,
                'reference' => 'ALN-878',
                'designation' => 'MAIN COURANTE',
                'slug' => 'aln-878-main-courante',
                'type_composant_id' => 1,
                'gamme_id' => NULL,
                'matiere' => NULL,
                'longueur_barre_mm' => NULL,
                'section_largeur_mm' => NULL,
                'section_hauteur_mm' => NULL,
                'epaisseur_paroi_mm' => NULL,
                'poids_lineaire_kg_m' => '0.740',
                'poids_lineaire_lbs_ft' => '0.497',
                'moment_inertie_cm4' => NULL,
                'perimetre_mm' => '291.08',
                'image_coupe' => NULL,
                'est_disponible' => 1,
                'created_at' => '2026-09-14 19:39:48',
                'updated_at' => '2026-09-15 19:20:11',
            ),
            9 => 
            array (
                'id' => 20,
                'reference' => 'ALN-877',
                'designation' => 'VERTICAL',
                'slug' => 'aln-877-vertical',
                'type_composant_id' => 1,
                'gamme_id' => NULL,
                'matiere' => NULL,
                'longueur_barre_mm' => NULL,
                'section_largeur_mm' => NULL,
                'section_hauteur_mm' => NULL,
                'epaisseur_paroi_mm' => NULL,
                'poids_lineaire_kg_m' => '0.820',
                'poids_lineaire_lbs_ft' => '0.551',
                'moment_inertie_cm4' => NULL,
                'perimetre_mm' => '253.59',
                'image_coupe' => NULL,
                'est_disponible' => 1,
                'created_at' => '2026-09-14 19:40:41',
                'updated_at' => '2026-09-15 19:20:11',
            ),
            10 => 
            array (
                'id' => 21,
                'reference' => 'ALN-1300',
                'designation' => 'BARREAU HEXAGONAL PETIT',
                'slug' => 'aln-1300-barreau-hexagonal-petit',
                'type_composant_id' => 1,
                'gamme_id' => NULL,
                'matiere' => NULL,
                'longueur_barre_mm' => NULL,
                'section_largeur_mm' => NULL,
                'section_hauteur_mm' => NULL,
                'epaisseur_paroi_mm' => NULL,
                'poids_lineaire_kg_m' => '0.285',
                'poids_lineaire_lbs_ft' => '0.192',
                'moment_inertie_cm4' => NULL,
                'perimetre_mm' => '77.64',
                'image_coupe' => NULL,
                'est_disponible' => 1,
                'created_at' => '2026-09-14 19:41:20',
                'updated_at' => '2026-09-15 19:20:11',
            ),
            11 => 
            array (
                'id' => 22,
                'reference' => 'ALN-1301',
                'designation' => 'BARREAU',
                'slug' => 'aln-1301-barreau',
                'type_composant_id' => 1,
                'gamme_id' => NULL,
                'matiere' => NULL,
                'longueur_barre_mm' => NULL,
                'section_largeur_mm' => NULL,
                'section_hauteur_mm' => NULL,
                'epaisseur_paroi_mm' => NULL,
                'poids_lineaire_kg_m' => '0.354',
                'poids_lineaire_lbs_ft' => '0.238',
                'moment_inertie_cm4' => NULL,
                'perimetre_mm' => '83.97',
                'image_coupe' => NULL,
                'est_disponible' => 1,
                'created_at' => '2026-09-14 19:41:51',
                'updated_at' => '2026-09-15 19:20:11',
            ),
            12 => 
            array (
                'id' => 23,
                'reference' => 'STC016',
                'designation' => 'ANCLAJES BARANDAS',
                'slug' => 'stc016-anclajes-barandas',
                'type_composant_id' => 1,
                'gamme_id' => NULL,
                'matiere' => NULL,
                'longueur_barre_mm' => NULL,
                'section_largeur_mm' => NULL,
                'section_hauteur_mm' => NULL,
                'epaisseur_paroi_mm' => NULL,
                'poids_lineaire_kg_m' => '4.708',
                'poids_lineaire_lbs_ft' => '3.164',
                'moment_inertie_cm4' => '11.860',
                'perimetre_mm' => '301.21',
                'image_coupe' => NULL,
                'est_disponible' => 1,
                'created_at' => '2026-09-15 18:37:38',
                'updated_at' => '2026-09-15 19:20:11',
            ),
            13 => 
            array (
                'id' => 25,
                'reference' => 'STC017',
                'designation' => 'ANCLAJES BARANDAS',
                'slug' => 'stc017-anclajes-barandas',
                'type_composant_id' => 1,
                'gamme_id' => NULL,
                'matiere' => NULL,
                'longueur_barre_mm' => NULL,
                'section_largeur_mm' => NULL,
                'section_hauteur_mm' => NULL,
                'epaisseur_paroi_mm' => NULL,
                'poids_lineaire_kg_m' => '3.673',
                'poids_lineaire_lbs_ft' => '2.468',
                'moment_inertie_cm4' => NULL,
                'perimetre_mm' => '244.93',
                'image_coupe' => NULL,
                'est_disponible' => 1,
                'created_at' => '2026-09-15 18:53:49',
                'updated_at' => '2026-09-15 19:20:11',
            ),
            14 => 
            array (
                'id' => 26,
                'reference' => 'STC018',
                'designation' => 'ANCLAJES BARANDAS',
                'slug' => 'stc018-anclajes-barandas',
                'type_composant_id' => 1,
                'gamme_id' => NULL,
                'matiere' => NULL,
                'longueur_barre_mm' => NULL,
                'section_largeur_mm' => NULL,
                'section_hauteur_mm' => NULL,
                'epaisseur_paroi_mm' => NULL,
                'poids_lineaire_kg_m' => '5.019',
                'poids_lineaire_lbs_ft' => '3.373',
                'moment_inertie_cm4' => NULL,
                'perimetre_mm' => '327.62',
                'image_coupe' => NULL,
                'est_disponible' => 1,
                'created_at' => '2026-09-15 18:55:41',
                'updated_at' => '2026-09-15 19:20:11',
            ),
            15 => 
            array (
                'id' => 27,
                'reference' => 'STC022',
                'designation' => 'ANCLAJES BARANDAS',
                'slug' => 'stc022-anclajes-barandas',
                'type_composant_id' => 1,
                'gamme_id' => NULL,
                'matiere' => NULL,
                'longueur_barre_mm' => NULL,
                'section_largeur_mm' => NULL,
                'section_hauteur_mm' => NULL,
                'epaisseur_paroi_mm' => NULL,
                'poids_lineaire_kg_m' => '1.101',
                'poids_lineaire_lbs_ft' => '0.740',
                'moment_inertie_cm4' => NULL,
                'perimetre_mm' => '116.57',
                'image_coupe' => NULL,
                'est_disponible' => 1,
                'created_at' => '2026-09-15 18:57:33',
                'updated_at' => '2026-09-15 19:20:11',
            ),
            16 => 
            array (
                'id' => 28,
                'reference' => 'STC023',
                'designation' => 'ANCLAJES BARANDAS',
                'slug' => 'stc023-anclajes-barandas',
                'type_composant_id' => 1,
                'gamme_id' => NULL,
                'matiere' => NULL,
                'longueur_barre_mm' => NULL,
                'section_largeur_mm' => NULL,
                'section_hauteur_mm' => NULL,
                'epaisseur_paroi_mm' => NULL,
                'poids_lineaire_kg_m' => '4.397',
                'poids_lineaire_lbs_ft' => '2.955',
                'moment_inertie_cm4' => NULL,
                'perimetre_mm' => '281.72',
                'image_coupe' => NULL,
                'est_disponible' => 1,
                'created_at' => '2026-09-15 18:59:22',
                'updated_at' => '2026-09-15 19:20:11',
            ),
            17 => 
            array (
                'id' => 29,
                'reference' => 'STC025',
                'designation' => 'ANCLAJES BARANDAS',
                'slug' => 'stc025-anclajes-barandas',
                'type_composant_id' => 1,
                'gamme_id' => NULL,
                'matiere' => NULL,
                'longueur_barre_mm' => NULL,
                'section_largeur_mm' => NULL,
                'section_hauteur_mm' => NULL,
                'epaisseur_paroi_mm' => NULL,
                'poids_lineaire_kg_m' => '0.700',
                'poids_lineaire_lbs_ft' => '0.470',
                'moment_inertie_cm4' => NULL,
                'perimetre_mm' => '238.23',
                'image_coupe' => NULL,
                'est_disponible' => 1,
                'created_at' => '2026-09-15 19:00:10',
                'updated_at' => '2026-09-15 19:20:11',
            ),
            18 => 
            array (
                'id' => 30,
                'reference' => 'STC020',
                'designation' => 'ANCLAJES BARANDAS',
                'slug' => 'stc020-anclajes-barandas',
                'type_composant_id' => 1,
                'gamme_id' => NULL,
                'matiere' => NULL,
                'longueur_barre_mm' => NULL,
                'section_largeur_mm' => NULL,
                'section_hauteur_mm' => NULL,
                'epaisseur_paroi_mm' => NULL,
                'poids_lineaire_kg_m' => '2.036',
                'poids_lineaire_lbs_ft' => '1.368',
                'moment_inertie_cm4' => NULL,
                'perimetre_mm' => '176.04',
                'image_coupe' => NULL,
                'est_disponible' => 1,
                'created_at' => '2026-09-15 19:01:05',
                'updated_at' => '2026-09-15 19:20:11',
            ),
            19 => 
            array (
                'id' => 31,
                'reference' => 'STC021',
                'designation' => 'ANCLAJES BARANDAS',
                'slug' => 'stc021-anclajes-barandas',
                'type_composant_id' => 1,
                'gamme_id' => NULL,
                'matiere' => NULL,
                'longueur_barre_mm' => NULL,
                'section_largeur_mm' => NULL,
                'section_hauteur_mm' => NULL,
                'epaisseur_paroi_mm' => NULL,
                'poids_lineaire_kg_m' => '1.010',
                'poids_lineaire_lbs_ft' => '0.679',
                'moment_inertie_cm4' => NULL,
                'perimetre_mm' => '144.67',
                'image_coupe' => NULL,
                'est_disponible' => 1,
                'created_at' => '2026-09-15 19:01:58',
                'updated_at' => '2026-09-15 19:20:11',
            ),
            20 => 
            array (
                'id' => 32,
                'reference' => 'STC024',
                'designation' => 'ANCLAJES BARANDAS',
                'slug' => 'stc024-anclajes-barandas',
                'type_composant_id' => 1,
                'gamme_id' => NULL,
                'matiere' => NULL,
                'longueur_barre_mm' => NULL,
                'section_largeur_mm' => NULL,
                'section_hauteur_mm' => NULL,
                'epaisseur_paroi_mm' => NULL,
                'poids_lineaire_kg_m' => '3.607',
                'poids_lineaire_lbs_ft' => '2.424',
                'moment_inertie_cm4' => NULL,
                'perimetre_mm' => '334.17',
                'image_coupe' => NULL,
                'est_disponible' => 1,
                'created_at' => '2026-09-15 19:02:53',
                'updated_at' => '2026-09-15 19:20:11',
            ),
            21 => 
            array (
                'id' => 33,
                'reference' => 'ALN-876',
                'designation' => 'ELEMENTO DIAGONAL',
                'slug' => 'aln-876-elemento-diagonal',
                'type_composant_id' => 1,
                'gamme_id' => NULL,
                'matiere' => NULL,
                'longueur_barre_mm' => NULL,
                'section_largeur_mm' => NULL,
                'section_hauteur_mm' => NULL,
                'epaisseur_paroi_mm' => NULL,
                'poids_lineaire_kg_m' => '0.548',
                'poids_lineaire_lbs_ft' => '0.368',
                'moment_inertie_cm4' => NULL,
                'perimetre_mm' => '205.39',
                'image_coupe' => NULL,
                'est_disponible' => 1,
                'created_at' => '2026-09-15 19:29:15',
                'updated_at' => '2026-09-15 19:34:05',
            ),
            22 => 
            array (
                'id' => 34,
                'reference' => 'ALN-877',
                'designation' => 'ELEMENTO VERTICAL',
                'slug' => 'aln-877-elemento-vertical',
                'type_composant_id' => 1,
                'gamme_id' => NULL,
                'matiere' => NULL,
                'longueur_barre_mm' => NULL,
                'section_largeur_mm' => NULL,
                'section_hauteur_mm' => NULL,
                'epaisseur_paroi_mm' => NULL,
                'poids_lineaire_kg_m' => '0.820',
                'poids_lineaire_lbs_ft' => '0.551',
                'moment_inertie_cm4' => NULL,
                'perimetre_mm' => '253.59',
                'image_coupe' => NULL,
                'est_disponible' => 1,
                'created_at' => '2026-09-15 19:35:11',
                'updated_at' => '2026-09-15 19:35:11',
            ),
            23 => 
            array (
                'id' => 35,
                'reference' => 'ALN-937',
                'designation' => 'BARROTE',
                'slug' => 'aln-937-barrote',
                'type_composant_id' => 1,
                'gamme_id' => NULL,
                'matiere' => NULL,
                'longueur_barre_mm' => NULL,
                'section_largeur_mm' => NULL,
                'section_hauteur_mm' => NULL,
                'epaisseur_paroi_mm' => NULL,
                'poids_lineaire_kg_m' => '0.427',
                'poids_lineaire_lbs_ft' => '0.287',
                'moment_inertie_cm4' => NULL,
                'perimetre_mm' => '87.66',
                'image_coupe' => NULL,
                'est_disponible' => 1,
                'created_at' => '2026-09-15 19:36:01',
                'updated_at' => '2026-09-15 19:36:01',
            ),
            24 => 
            array (
                'id' => 36,
                'reference' => 'ALN-879',
                'designation' => 'TAPA',
                'slug' => 'aln-879-tapa',
                'type_composant_id' => 1,
                'gamme_id' => NULL,
                'matiere' => NULL,
                'longueur_barre_mm' => NULL,
                'section_largeur_mm' => NULL,
                'section_hauteur_mm' => NULL,
                'epaisseur_paroi_mm' => NULL,
                'poids_lineaire_kg_m' => '0.385',
                'poids_lineaire_lbs_ft' => '0.259',
                'moment_inertie_cm4' => NULL,
                'perimetre_mm' => '150.01',
                'image_coupe' => NULL,
                'est_disponible' => 1,
                'created_at' => '2026-09-15 19:36:47',
                'updated_at' => '2026-09-15 19:36:47',
            ),
            25 => 
            array (
                'id' => 37,
                'reference' => 'F-014',
                'designation' => 'LAME DE REMPLISSAGE BAS DE PORTAIL',
                'slug' => 'f-014-lame-de-remplissage-bas-de-portail',
                'type_composant_id' => 1,
                'gamme_id' => NULL,
                'matiere' => NULL,
                'longueur_barre_mm' => NULL,
                'section_largeur_mm' => NULL,
                'section_hauteur_mm' => NULL,
                'epaisseur_paroi_mm' => NULL,
                'poids_lineaire_kg_m' => '0.408',
                'poids_lineaire_lbs_ft' => '0.274',
                'moment_inertie_cm4' => NULL,
                'perimetre_mm' => '220.43',
                'image_coupe' => NULL,
                'est_disponible' => 1,
                'created_at' => '2026-09-15 20:35:15',
                'updated_at' => '2026-09-15 20:35:15',
            ),
            26 => 
            array (
                'id' => 38,
                'reference' => 'ALN-1097',
                'designation' => 'CADRE PORTAIL',
                'slug' => 'aln-1097-cadre-portail',
                'type_composant_id' => 1,
                'gamme_id' => NULL,
                'matiere' => NULL,
                'longueur_barre_mm' => NULL,
                'section_largeur_mm' => NULL,
                'section_hauteur_mm' => NULL,
                'epaisseur_paroi_mm' => NULL,
                'poids_lineaire_kg_m' => '1.168',
                'poids_lineaire_lbs_ft' => '0.785',
                'moment_inertie_cm4' => NULL,
                'perimetre_mm' => '250.80',
                'image_coupe' => NULL,
                'est_disponible' => 1,
                'created_at' => '2026-09-15 20:36:00',
                'updated_at' => '2026-09-15 20:36:00',
            ),
            27 => 
            array (
                'id' => 39,
                'reference' => 'ALN-1057',
                'designation' => 'SUPPORT LAME',
                'slug' => 'aln-1057-support-lame',
                'type_composant_id' => 1,
                'gamme_id' => NULL,
                'matiere' => NULL,
                'longueur_barre_mm' => NULL,
                'section_largeur_mm' => NULL,
                'section_hauteur_mm' => NULL,
                'epaisseur_paroi_mm' => NULL,
                'poids_lineaire_kg_m' => '0.336',
                'poids_lineaire_lbs_ft' => '0.226',
                'moment_inertie_cm4' => NULL,
                'perimetre_mm' => '128.41',
                'image_coupe' => NULL,
                'est_disponible' => 1,
                'created_at' => '2026-09-15 20:36:40',
                'updated_at' => '2026-09-15 20:36:40',
            ),
            28 => 
            array (
                'id' => 40,
                'reference' => 'ALN-1244',
                'designation' => 'BUTTE DE PORTE',
                'slug' => 'aln-1244-butte-de-porte',
                'type_composant_id' => 1,
                'gamme_id' => NULL,
                'matiere' => NULL,
                'longueur_barre_mm' => NULL,
                'section_largeur_mm' => NULL,
                'section_hauteur_mm' => NULL,
                'epaisseur_paroi_mm' => NULL,
                'poids_lineaire_kg_m' => '0.421',
                'poids_lineaire_lbs_ft' => '0.283',
                'moment_inertie_cm4' => NULL,
                'perimetre_mm' => '139.24',
                'image_coupe' => NULL,
                'est_disponible' => 1,
                'created_at' => '2026-09-15 20:37:19',
                'updated_at' => '2026-09-15 20:37:19',
            ),
            29 => 
            array (
                'id' => 41,
                'reference' => 'ALN-1099',
                'designation' => 'PROFILE UNION CENTRAL',
                'slug' => 'aln-1099-profile-union-central',
                'type_composant_id' => 1,
                'gamme_id' => NULL,
                'matiere' => NULL,
                'longueur_barre_mm' => NULL,
                'section_largeur_mm' => NULL,
                'section_hauteur_mm' => NULL,
                'epaisseur_paroi_mm' => NULL,
                'poids_lineaire_kg_m' => '1.107',
                'poids_lineaire_lbs_ft' => '0.744',
                'moment_inertie_cm4' => NULL,
                'perimetre_mm' => '222.23',
                'image_coupe' => NULL,
                'est_disponible' => 1,
                'created_at' => '2026-09-15 20:38:59',
                'updated_at' => '2026-09-15 20:38:59',
            ),
            30 => 
            array (
                'id' => 42,
                'reference' => 'ALN-1098',
                'designation' => 'ANGLE DE FIXATION CADRE',
                'slug' => 'aln-1098-angle-de-fixation-cadre',
                'type_composant_id' => 1,
                'gamme_id' => NULL,
                'matiere' => NULL,
                'longueur_barre_mm' => NULL,
                'section_largeur_mm' => NULL,
                'section_hauteur_mm' => NULL,
                'epaisseur_paroi_mm' => NULL,
                'poids_lineaire_kg_m' => '9.919',
                'poids_lineaire_lbs_ft' => '6.666',
                'moment_inertie_cm4' => NULL,
                'perimetre_mm' => '538.99',
                'image_coupe' => NULL,
                'est_disponible' => 1,
                'created_at' => '2026-09-15 20:39:40',
                'updated_at' => '2026-09-15 20:39:40',
            ),
            31 => 
            array (
                'id' => 43,
                'reference' => 'ALN-988',
                'designation' => 'LAME RANCH',
                'slug' => 'aln-988-lame-ranch',
                'type_composant_id' => 1,
                'gamme_id' => NULL,
                'matiere' => NULL,
                'longueur_barre_mm' => NULL,
                'section_largeur_mm' => NULL,
                'section_hauteur_mm' => NULL,
                'epaisseur_paroi_mm' => NULL,
                'poids_lineaire_kg_m' => '0.691',
                'poids_lineaire_lbs_ft' => '0.464',
                'moment_inertie_cm4' => NULL,
                'perimetre_mm' => '191.80',
                'image_coupe' => NULL,
                'est_disponible' => 1,
                'created_at' => '2026-09-15 20:44:13',
                'updated_at' => '2026-09-15 20:44:13',
            ),
            32 => 
            array (
                'id' => 44,
                'reference' => 'ALN-1097',
                'designation' => 'MARCO NAVE',
                'slug' => 'aln-1097-marco-nave',
                'type_composant_id' => 1,
                'gamme_id' => NULL,
                'matiere' => NULL,
                'longueur_barre_mm' => NULL,
                'section_largeur_mm' => NULL,
                'section_hauteur_mm' => NULL,
                'epaisseur_paroi_mm' => NULL,
                'poids_lineaire_kg_m' => '1.168',
                'poids_lineaire_lbs_ft' => '0.785',
                'moment_inertie_cm4' => NULL,
                'perimetre_mm' => '250.80',
                'image_coupe' => NULL,
                'est_disponible' => 1,
                'created_at' => '2026-09-15 20:44:49',
                'updated_at' => '2026-09-15 20:44:49',
            ),
            33 => 
            array (
                'id' => 45,
                'reference' => 'U-107',
                'designation' => 'MARCO',
                'slug' => 'u-107-marco',
                'type_composant_id' => 1,
                'gamme_id' => NULL,
                'matiere' => NULL,
                'longueur_barre_mm' => NULL,
                'section_largeur_mm' => NULL,
                'section_hauteur_mm' => NULL,
                'epaisseur_paroi_mm' => NULL,
                'poids_lineaire_kg_m' => '1.080',
                'poids_lineaire_lbs_ft' => '0.726',
                'moment_inertie_cm4' => NULL,
                'perimetre_mm' => '446.20',
                'image_coupe' => NULL,
                'est_disponible' => 1,
                'created_at' => '2026-09-15 20:45:29',
                'updated_at' => '2026-09-15 20:45:29',
            ),
            34 => 
            array (
                'id' => 46,
                'reference' => 'ALN-1247',
                'designation' => 'LAME',
                'slug' => 'aln-1247-lame',
                'type_composant_id' => 1,
                'gamme_id' => NULL,
                'matiere' => NULL,
                'longueur_barre_mm' => NULL,
                'section_largeur_mm' => NULL,
                'section_hauteur_mm' => NULL,
                'epaisseur_paroi_mm' => NULL,
                'poids_lineaire_kg_m' => '0.459',
                'poids_lineaire_lbs_ft' => '0.308',
                'moment_inertie_cm4' => NULL,
                'perimetre_mm' => '204.55',
                'image_coupe' => NULL,
                'est_disponible' => 1,
                'created_at' => '2026-09-15 20:48:14',
                'updated_at' => '2026-09-15 20:48:14',
            ),
            35 => 
            array (
                'id' => 47,
                'reference' => 'U-118',
                'designation' => 'SUPPORT LAME RANCH',
                'slug' => 'u-118-support-lame-ranch',
                'type_composant_id' => 1,
                'gamme_id' => NULL,
                'matiere' => NULL,
                'longueur_barre_mm' => NULL,
                'section_largeur_mm' => NULL,
                'section_hauteur_mm' => NULL,
                'epaisseur_paroi_mm' => NULL,
                'poids_lineaire_kg_m' => '0.211',
                'poids_lineaire_lbs_ft' => '0.142',
                'moment_inertie_cm4' => NULL,
                'perimetre_mm' => '107.85',
                'image_coupe' => NULL,
                'est_disponible' => 1,
                'created_at' => '2026-09-15 21:37:53',
                'updated_at' => '2026-09-15 21:37:53',
            ),
            36 => 
            array (
                'id' => 48,
                'reference' => 'ALN-1568',
                'designation' => 'PROFILES DE PORTES',
                'slug' => 'aln-1568-profiles-de-portes',
                'type_composant_id' => 1,
                'gamme_id' => NULL,
                'matiere' => NULL,
                'longueur_barre_mm' => NULL,
                'section_largeur_mm' => NULL,
                'section_hauteur_mm' => NULL,
                'epaisseur_paroi_mm' => NULL,
                'poids_lineaire_kg_m' => '0.661',
                'poids_lineaire_lbs_ft' => '0.444',
                'moment_inertie_cm4' => NULL,
                'perimetre_mm' => '256.33',
                'image_coupe' => NULL,
                'est_disponible' => 1,
                'created_at' => '2026-09-18 18:22:24',
                'updated_at' => '2026-09-18 18:22:24',
            ),
            37 => 
            array (
                'id' => 49,
                'reference' => 'ALN-1569',
                'designation' => 'PROFILES DE PORTES',
                'slug' => 'aln-1569-profiles-de-portes',
                'type_composant_id' => 1,
                'gamme_id' => NULL,
                'matiere' => NULL,
                'longueur_barre_mm' => NULL,
                'section_largeur_mm' => NULL,
                'section_hauteur_mm' => NULL,
                'epaisseur_paroi_mm' => NULL,
                'poids_lineaire_kg_m' => '0.421',
                'poids_lineaire_lbs_ft' => '0.283',
                'moment_inertie_cm4' => NULL,
                'perimetre_mm' => '238.52',
                'image_coupe' => NULL,
                'est_disponible' => 1,
                'created_at' => '2026-09-18 18:23:16',
                'updated_at' => '2026-09-18 18:23:16',
            ),
            38 => 
            array (
                'id' => 50,
                'reference' => 'ALN-1570',
                'designation' => 'PROFILES DE PORTES',
                'slug' => 'aln-1570-profiles-de-portes',
                'type_composant_id' => 1,
                'gamme_id' => NULL,
                'matiere' => NULL,
                'longueur_barre_mm' => NULL,
                'section_largeur_mm' => NULL,
                'section_hauteur_mm' => NULL,
                'epaisseur_paroi_mm' => NULL,
                'poids_lineaire_kg_m' => '0.892',
                'poids_lineaire_lbs_ft' => '0.599',
                'moment_inertie_cm4' => NULL,
                'perimetre_mm' => '289.17',
                'image_coupe' => NULL,
                'est_disponible' => 1,
                'created_at' => '2026-09-18 18:24:24',
                'updated_at' => '2026-09-18 18:24:24',
            ),
            39 => 
            array (
                'id' => 51,
                'reference' => 'ALN-1571',
                'designation' => 'PROFILES DE PORTES',
                'slug' => 'aln-1571-profiles-de-portes',
                'type_composant_id' => 1,
                'gamme_id' => NULL,
                'matiere' => NULL,
                'longueur_barre_mm' => NULL,
                'section_largeur_mm' => NULL,
                'section_hauteur_mm' => NULL,
                'epaisseur_paroi_mm' => NULL,
                'poids_lineaire_kg_m' => '0.743',
                'poids_lineaire_lbs_ft' => '0.499',
                'moment_inertie_cm4' => NULL,
                'perimetre_mm' => '187.24',
                'image_coupe' => NULL,
                'est_disponible' => 1,
                'created_at' => '2026-09-18 18:25:35',
                'updated_at' => '2026-09-18 18:25:35',
            ),
            40 => 
            array (
                'id' => 52,
                'reference' => 'ALN-1572',
                'designation' => 'PROFILES DE PORTES',
                'slug' => 'aln-1572-profiles-de-portes',
                'type_composant_id' => 1,
                'gamme_id' => NULL,
                'matiere' => NULL,
                'longueur_barre_mm' => NULL,
                'section_largeur_mm' => NULL,
                'section_hauteur_mm' => NULL,
                'epaisseur_paroi_mm' => NULL,
                'poids_lineaire_kg_m' => '0.621',
                'poids_lineaire_lbs_ft' => '0.417',
                'moment_inertie_cm4' => NULL,
                'perimetre_mm' => '170.40',
                'image_coupe' => NULL,
                'est_disponible' => 1,
                'created_at' => '2026-09-18 18:26:47',
                'updated_at' => '2026-09-18 18:26:47',
            ),
            41 => 
            array (
                'id' => 53,
                'reference' => 'ALN-988',
                'designation' => 'BARROTE',
                'slug' => 'aln-988-barrote',
                'type_composant_id' => 1,
                'gamme_id' => NULL,
                'matiere' => NULL,
                'longueur_barre_mm' => NULL,
                'section_largeur_mm' => NULL,
                'section_hauteur_mm' => NULL,
                'epaisseur_paroi_mm' => NULL,
                'poids_lineaire_kg_m' => '0.691',
                'poids_lineaire_lbs_ft' => '0.464',
                'moment_inertie_cm4' => NULL,
                'perimetre_mm' => '191.86',
                'image_coupe' => NULL,
                'est_disponible' => 1,
                'created_at' => '2026-09-18 18:30:36',
                'updated_at' => '2026-09-18 18:30:36',
            ),
            42 => 
            array (
                'id' => 54,
                'reference' => 'ALN-183',
                'designation' => 'CANAL LISA',
                'slug' => 'aln-183-canal-lisa',
                'type_composant_id' => 1,
                'gamme_id' => NULL,
                'matiere' => NULL,
                'longueur_barre_mm' => NULL,
                'section_largeur_mm' => NULL,
                'section_hauteur_mm' => NULL,
                'epaisseur_paroi_mm' => NULL,
                'poids_lineaire_kg_m' => '0.877',
                'poids_lineaire_lbs_ft' => '0.589',
                'moment_inertie_cm4' => NULL,
                'perimetre_mm' => '357.29',
                'image_coupe' => NULL,
                'est_disponible' => 1,
                'created_at' => '2026-09-18 18:32:19',
                'updated_at' => '2026-09-18 18:32:19',
            ),
            43 => 
            array (
                'id' => 55,
                'reference' => 'T-086',
                'designation' => 'TUBE CARRE',
                'slug' => 't-086-tube-carre',
                'type_composant_id' => 1,
                'gamme_id' => NULL,
                'matiere' => NULL,
                'longueur_barre_mm' => NULL,
                'section_largeur_mm' => NULL,
                'section_hauteur_mm' => NULL,
                'epaisseur_paroi_mm' => NULL,
                'poids_lineaire_kg_m' => '3.037',
                'poids_lineaire_lbs_ft' => '2.041',
                'moment_inertie_cm4' => NULL,
                'perimetre_mm' => '359.31',
                'image_coupe' => NULL,
                'est_disponible' => 1,
                'created_at' => '2026-09-18 18:33:31',
                'updated_at' => '2026-09-18 18:33:31',
            ),
            44 => 
            array (
                'id' => 56,
                'reference' => 'ALN-170',
                'designation' => 'TAPA LISA',
                'slug' => 'aln-170-tapa-lisa',
                'type_composant_id' => 1,
                'gamme_id' => NULL,
                'matiere' => NULL,
                'longueur_barre_mm' => NULL,
                'section_largeur_mm' => NULL,
                'section_hauteur_mm' => NULL,
                'epaisseur_paroi_mm' => NULL,
                'poids_lineaire_kg_m' => '0.364',
                'poids_lineaire_lbs_ft' => '0.245',
                'moment_inertie_cm4' => NULL,
                'perimetre_mm' => '176.13',
                'image_coupe' => NULL,
                'est_disponible' => 1,
                'created_at' => '2026-09-18 18:34:20',
                'updated_at' => '2026-09-18 18:34:20',
            ),
            45 => 
            array (
                'id' => 57,
                'reference' => 'T-264',
                'designation' => 'PASAMANOS Y REJAS',
                'slug' => 't-264-pasamanos-y-rejas',
                'type_composant_id' => 1,
                'gamme_id' => NULL,
                'matiere' => NULL,
                'longueur_barre_mm' => NULL,
                'section_largeur_mm' => NULL,
                'section_hauteur_mm' => NULL,
                'epaisseur_paroi_mm' => NULL,
                'poids_lineaire_kg_m' => '1.946',
                'poids_lineaire_lbs_ft' => '1.308',
                'moment_inertie_cm4' => NULL,
                'perimetre_mm' => '319.14',
                'image_coupe' => NULL,
                'est_disponible' => 1,
                'created_at' => '2026-09-18 18:48:27',
                'updated_at' => '2026-09-18 18:48:27',
            ),
            46 => 
            array (
                'id' => 58,
                'reference' => 'ALN-1496',
                'designation' => 'PASAMANOS Y REJAS',
                'slug' => 'aln-1496-pasamanos-y-rejas',
                'type_composant_id' => 1,
                'gamme_id' => NULL,
                'matiere' => NULL,
                'longueur_barre_mm' => NULL,
                'section_largeur_mm' => NULL,
                'section_hauteur_mm' => NULL,
                'epaisseur_paroi_mm' => NULL,
                'poids_lineaire_kg_m' => '0.335',
                'poids_lineaire_lbs_ft' => '0.225',
                'moment_inertie_cm4' => NULL,
                'perimetre_mm' => '158.13',
                'image_coupe' => NULL,
                'est_disponible' => 1,
                'created_at' => '2026-09-18 18:49:46',
                'updated_at' => '2026-09-18 18:49:46',
            ),
            47 => 
            array (
                'id' => 59,
                'reference' => 'ALN-1583',
                'designation' => 'PASAMANOS Y REJAS',
                'slug' => 'aln-1583-pasamanos-y-rejas',
                'type_composant_id' => 1,
                'gamme_id' => NULL,
                'matiere' => NULL,
                'longueur_barre_mm' => NULL,
                'section_largeur_mm' => NULL,
                'section_hauteur_mm' => NULL,
                'epaisseur_paroi_mm' => NULL,
                'poids_lineaire_kg_m' => '0.919',
                'poids_lineaire_lbs_ft' => '0.618',
                'moment_inertie_cm4' => NULL,
                'perimetre_mm' => '402.63',
                'image_coupe' => NULL,
                'est_disponible' => 1,
                'created_at' => '2026-09-18 18:52:22',
                'updated_at' => '2026-09-18 18:52:22',
            ),
            48 => 
            array (
                'id' => 60,
                'reference' => 'ALN-1534',
                'designation' => 'PASAMANOS Y REJAS',
                'slug' => 'aln-1534-pasamanos-y-rejas',
                'type_composant_id' => 1,
                'gamme_id' => NULL,
                'matiere' => NULL,
                'longueur_barre_mm' => NULL,
                'section_largeur_mm' => NULL,
                'section_hauteur_mm' => NULL,
                'epaisseur_paroi_mm' => NULL,
                'poids_lineaire_kg_m' => '0.810',
                'poids_lineaire_lbs_ft' => '0.544',
                'moment_inertie_cm4' => NULL,
                'perimetre_mm' => '249.25',
                'image_coupe' => NULL,
                'est_disponible' => 1,
                'created_at' => '2026-09-18 18:53:40',
                'updated_at' => '2026-09-18 18:53:40',
            ),
            49 => 
            array (
                'id' => 61,
                'reference' => 'ALN-1535',
                'designation' => 'PASAMANOS Y REJAS',
                'slug' => 'aln-1535-pasamanos-y-rejas',
                'type_composant_id' => 1,
                'gamme_id' => NULL,
                'matiere' => NULL,
                'longueur_barre_mm' => NULL,
                'section_largeur_mm' => NULL,
                'section_hauteur_mm' => NULL,
                'epaisseur_paroi_mm' => NULL,
                'poids_lineaire_kg_m' => '0.409',
                'poids_lineaire_lbs_ft' => '0.275',
                'moment_inertie_cm4' => NULL,
                'perimetre_mm' => '187.70',
                'image_coupe' => NULL,
                'est_disponible' => 1,
                'created_at' => '2026-09-18 18:54:23',
                'updated_at' => '2026-09-18 18:54:23',
            ),
            50 => 
            array (
                'id' => 62,
                'reference' => 'ALN-1536',
                'designation' => 'PASAMANOS Y REJAS',
                'slug' => 'aln-1536-pasamanos-y-rejas',
                'type_composant_id' => 1,
                'gamme_id' => NULL,
                'matiere' => NULL,
                'longueur_barre_mm' => NULL,
                'section_largeur_mm' => NULL,
                'section_hauteur_mm' => NULL,
                'epaisseur_paroi_mm' => NULL,
                'poids_lineaire_kg_m' => '0.261',
                'poids_lineaire_lbs_ft' => '0.175',
                'moment_inertie_cm4' => '5.130',
                'perimetre_mm' => '130.29',
                'image_coupe' => NULL,
                'est_disponible' => 1,
                'created_at' => '2026-09-18 18:55:12',
                'updated_at' => '2026-09-18 18:55:19',
            ),
            51 => 
            array (
                'id' => 63,
                'reference' => 'ALN-1240',
                'designation' => 'JAMBA',
                'slug' => 'aln-1240-jamba',
                'type_composant_id' => 1,
                'gamme_id' => NULL,
                'matiere' => NULL,
                'longueur_barre_mm' => NULL,
                'section_largeur_mm' => NULL,
                'section_hauteur_mm' => NULL,
                'epaisseur_paroi_mm' => NULL,
                'poids_lineaire_kg_m' => '0.706',
                'poids_lineaire_lbs_ft' => '0.474',
                'moment_inertie_cm4' => NULL,
                'perimetre_mm' => '285.99',
                'image_coupe' => NULL,
                'est_disponible' => 1,
                'created_at' => '2026-09-18 18:57:56',
                'updated_at' => '2026-09-18 19:15:55',
            ),
            52 => 
            array (
                'id' => 64,
                'reference' => 'ALN-1241',
                'designation' => 'JAMBA',
                'slug' => 'aln-1241-jamba',
                'type_composant_id' => 1,
                'gamme_id' => NULL,
                'matiere' => NULL,
                'longueur_barre_mm' => NULL,
                'section_largeur_mm' => NULL,
                'section_hauteur_mm' => NULL,
                'epaisseur_paroi_mm' => NULL,
                'poids_lineaire_kg_m' => '0.901',
                'poids_lineaire_lbs_ft' => '0.605',
                'moment_inertie_cm4' => '12.461',
                'perimetre_mm' => '316.50',
                'image_coupe' => NULL,
                'est_disponible' => 1,
                'created_at' => '2026-09-18 18:58:52',
                'updated_at' => '2026-09-18 19:19:28',
            ),
            53 => 
            array (
                'id' => 65,
                'reference' => 'ALN-1267',
                'designation' => 'JAMBA',
                'slug' => 'aln-1267-jamba',
                'type_composant_id' => 1,
                'gamme_id' => NULL,
                'matiere' => NULL,
                'longueur_barre_mm' => NULL,
                'section_largeur_mm' => NULL,
                'section_hauteur_mm' => NULL,
                'epaisseur_paroi_mm' => NULL,
                'poids_lineaire_kg_m' => '0.487',
                'poids_lineaire_lbs_ft' => '0.327',
                'moment_inertie_cm4' => '9.140',
                'perimetre_mm' => '232.02',
                'image_coupe' => NULL,
                'est_disponible' => 1,
                'created_at' => '2026-09-18 19:01:27',
                'updated_at' => '2026-09-18 19:06:58',
            ),
            54 => 
            array (
                'id' => 66,
                'reference' => 'ALN-1246',
                'designation' => 'LAMA FINAL',
                'slug' => 'aln-1246-lama-final',
                'type_composant_id' => 1,
                'gamme_id' => NULL,
                'matiere' => NULL,
                'longueur_barre_mm' => NULL,
                'section_largeur_mm' => NULL,
                'section_hauteur_mm' => NULL,
                'epaisseur_paroi_mm' => NULL,
                'poids_lineaire_kg_m' => '0.459',
                'poids_lineaire_lbs_ft' => '0.308',
                'moment_inertie_cm4' => '5.118',
                'perimetre_mm' => '170.86',
                'image_coupe' => NULL,
                'est_disponible' => 1,
                'created_at' => '2026-09-18 19:20:15',
                'updated_at' => '2026-09-18 19:20:15',
            ),
            55 => 
            array (
                'id' => 67,
                'reference' => 'ALN-1242',
                'designation' => 'JAMBA',
                'slug' => 'aln-1242-jamba',
                'type_composant_id' => 1,
                'gamme_id' => NULL,
                'matiere' => NULL,
                'longueur_barre_mm' => NULL,
                'section_largeur_mm' => NULL,
                'section_hauteur_mm' => NULL,
                'epaisseur_paroi_mm' => NULL,
                'poids_lineaire_kg_m' => '1.339',
                'poids_lineaire_lbs_ft' => '0.900',
                'moment_inertie_cm4' => '15.474',
                'perimetre_mm' => '393.05',
                'image_coupe' => NULL,
                'est_disponible' => 1,
                'created_at' => '2026-09-18 19:22:13',
                'updated_at' => '2026-09-18 19:22:13',
            ),
            56 => 
            array (
                'id' => 68,
                'reference' => 'ALN-1248',
                'designation' => 'LAMA FINAL',
                'slug' => 'aln-1248-lama-final',
                'type_composant_id' => 1,
                'gamme_id' => NULL,
                'matiere' => NULL,
                'longueur_barre_mm' => NULL,
                'section_largeur_mm' => NULL,
                'section_hauteur_mm' => NULL,
                'epaisseur_paroi_mm' => NULL,
                'poids_lineaire_kg_m' => '0.249',
                'poids_lineaire_lbs_ft' => '0.167',
                'moment_inertie_cm4' => '4.433',
                'perimetre_mm' => '112.61',
                'image_coupe' => NULL,
                'est_disponible' => 1,
                'created_at' => '2026-09-18 19:23:13',
                'updated_at' => '2026-09-18 19:23:13',
            ),
            57 => 
            array (
                'id' => 69,
                'reference' => 'ALN-1247',
                'designation' => 'LAMA INTERMEDIA',
                'slug' => 'aln-1247-lama-intermedia',
                'type_composant_id' => 1,
                'gamme_id' => NULL,
                'matiere' => NULL,
                'longueur_barre_mm' => NULL,
                'section_largeur_mm' => NULL,
                'section_hauteur_mm' => NULL,
                'epaisseur_paroi_mm' => NULL,
                'poids_lineaire_kg_m' => '0.459',
                'poids_lineaire_lbs_ft' => '0.308',
                'moment_inertie_cm4' => '5.482',
                'perimetre_mm' => '204.55',
                'image_coupe' => NULL,
                'est_disponible' => 1,
                'created_at' => '2026-09-18 19:24:01',
                'updated_at' => '2026-09-18 19:24:01',
            ),
            58 => 
            array (
                'id' => 70,
                'reference' => 'ALN-1249',
                'designation' => 'LAMA INTERMEDIA',
                'slug' => 'aln-1249-lama-intermedia',
                'type_composant_id' => 1,
                'gamme_id' => NULL,
                'matiere' => NULL,
                'longueur_barre_mm' => NULL,
                'section_largeur_mm' => NULL,
                'section_hauteur_mm' => NULL,
                'epaisseur_paroi_mm' => NULL,
                'poids_lineaire_kg_m' => '0.260',
                'poids_lineaire_lbs_ft' => '0.175',
                'moment_inertie_cm4' => '4.800',
                'perimetre_mm' => '121.91',
                'image_coupe' => NULL,
                'est_disponible' => 1,
                'created_at' => '2026-09-18 19:25:24',
                'updated_at' => '2026-09-18 19:25:24',
            ),
            59 => 
            array (
                'id' => 71,
                'reference' => 'ALN-1253',
                'designation' => 'LAMA INTERMEDIA',
                'slug' => 'aln-1253-lama-intermedia',
                'type_composant_id' => 1,
                'gamme_id' => NULL,
                'matiere' => NULL,
                'longueur_barre_mm' => NULL,
                'section_largeur_mm' => NULL,
                'section_hauteur_mm' => NULL,
                'epaisseur_paroi_mm' => NULL,
                'poids_lineaire_kg_m' => '0.313',
                'poids_lineaire_lbs_ft' => '0.210',
                'moment_inertie_cm4' => '5.797',
                'perimetre_mm' => '147.23',
                'image_coupe' => NULL,
                'est_disponible' => 1,
                'created_at' => '2026-09-18 19:26:31',
                'updated_at' => '2026-09-18 19:26:31',
            ),
            60 => 
            array (
                'id' => 72,
                'reference' => 'ALN-1254',
                'designation' => 'LAMA FINAL',
                'slug' => 'aln-1254-lama-final',
                'type_composant_id' => 1,
                'gamme_id' => NULL,
                'matiere' => NULL,
                'longueur_barre_mm' => NULL,
                'section_largeur_mm' => NULL,
                'section_hauteur_mm' => NULL,
                'epaisseur_paroi_mm' => NULL,
                'poids_lineaire_kg_m' => '0.302',
                'poids_lineaire_lbs_ft' => '0.203',
                'moment_inertie_cm4' => '5.229',
                'perimetre_mm' => '132.82',
                'image_coupe' => NULL,
                'est_disponible' => 1,
                'created_at' => '2026-09-18 19:27:29',
                'updated_at' => '2026-09-18 19:27:29',
            ),
            61 => 
            array (
                'id' => 73,
                'reference' => 'SVR-002',
                'designation' => 'PROFILES VARIES',
                'slug' => 'svr-002-profiles-varies',
                'type_composant_id' => 1,
                'gamme_id' => NULL,
                'matiere' => NULL,
                'longueur_barre_mm' => NULL,
                'section_largeur_mm' => NULL,
                'section_hauteur_mm' => NULL,
                'epaisseur_paroi_mm' => NULL,
                'poids_lineaire_kg_m' => '1.072',
                'poids_lineaire_lbs_ft' => '0.720',
                'moment_inertie_cm4' => '8.022',
                'perimetre_mm' => '203.75',
                'image_coupe' => NULL,
                'est_disponible' => 1,
                'created_at' => '2026-09-21 16:40:25',
                'updated_at' => '2026-09-21 16:40:25',
            ),
            62 => 
            array (
                'id' => 74,
                'reference' => 'SVR-003',
                'designation' => 'PROFILES VARIES',
                'slug' => 'svr-003-profiles-varies',
                'type_composant_id' => 1,
                'gamme_id' => NULL,
                'matiere' => NULL,
                'longueur_barre_mm' => NULL,
                'section_largeur_mm' => NULL,
                'section_hauteur_mm' => NULL,
                'epaisseur_paroi_mm' => NULL,
                'poids_lineaire_kg_m' => '1.257',
                'poids_lineaire_lbs_ft' => '0.845',
                'moment_inertie_cm4' => '9.372',
                'perimetre_mm' => '238.06',
                'image_coupe' => NULL,
                'est_disponible' => 1,
                'created_at' => '2026-09-21 16:41:47',
                'updated_at' => '2026-09-21 16:41:47',
            ),
            63 => 
            array (
                'id' => 75,
                'reference' => 'OJL-3005',
                'designation' => 'PROFILES VARIES',
                'slug' => 'ojl-3005-profiles-varies',
                'type_composant_id' => 1,
                'gamme_id' => NULL,
                'matiere' => NULL,
                'longueur_barre_mm' => NULL,
                'section_largeur_mm' => NULL,
                'section_hauteur_mm' => NULL,
                'epaisseur_paroi_mm' => NULL,
                'poids_lineaire_kg_m' => '0.744',
                'poids_lineaire_lbs_ft' => '0.500',
                'moment_inertie_cm4' => '7.357',
                'perimetre_mm' => '186.88',
                'image_coupe' => NULL,
                'est_disponible' => 1,
                'created_at' => '2026-09-21 16:42:45',
                'updated_at' => '2026-09-21 16:42:45',
            ),
            64 => 
            array (
                'id' => 76,
                'reference' => 'OD-9012',
                'designation' => 'PROFILES VARIES',
                'slug' => 'od-9012-profiles-varies',
                'type_composant_id' => 1,
                'gamme_id' => NULL,
                'matiere' => NULL,
                'longueur_barre_mm' => NULL,
                'section_largeur_mm' => NULL,
                'section_hauteur_mm' => NULL,
                'epaisseur_paroi_mm' => NULL,
                'poids_lineaire_kg_m' => '0.164',
                'poids_lineaire_lbs_ft' => '0.110',
                'moment_inertie_cm4' => '2.369',
                'perimetre_mm' => '83.03',
                'image_coupe' => NULL,
                'est_disponible' => 1,
                'created_at' => '2026-09-21 16:43:39',
                'updated_at' => '2026-09-21 16:43:39',
            ),
            65 => 
            array (
                'id' => 77,
                'reference' => 'STC-001',
                'designation' => 'PROFILES VARIES',
                'slug' => 'stc-001-profiles-varies',
                'type_composant_id' => 1,
                'gamme_id' => NULL,
                'matiere' => NULL,
                'longueur_barre_mm' => NULL,
                'section_largeur_mm' => NULL,
                'section_hauteur_mm' => NULL,
                'epaisseur_paroi_mm' => NULL,
                'poids_lineaire_kg_m' => '0.237',
                'poids_lineaire_lbs_ft' => '0.159',
                'moment_inertie_cm4' => '5.739',
                'perimetre_mm' => '145.76',
                'image_coupe' => NULL,
                'est_disponible' => 1,
                'created_at' => '2026-09-21 16:44:21',
                'updated_at' => '2026-09-21 16:44:21',
            ),
            66 => 
            array (
                'id' => 78,
                'reference' => 'SVR-001',
                'designation' => 'PROFILES VARIES',
                'slug' => 'svr-001-profiles-varies',
                'type_composant_id' => 1,
                'gamme_id' => NULL,
                'matiere' => NULL,
                'longueur_barre_mm' => NULL,
                'section_largeur_mm' => NULL,
                'section_hauteur_mm' => NULL,
                'epaisseur_paroi_mm' => NULL,
                'poids_lineaire_kg_m' => '0.964',
                'poids_lineaire_lbs_ft' => '0.648',
                'moment_inertie_cm4' => '13.928',
                'perimetre_mm' => '353.71',
                'image_coupe' => NULL,
                'est_disponible' => 1,
                'created_at' => '2026-09-21 16:47:30',
                'updated_at' => '2026-09-21 16:47:30',
            ),
            67 => 
            array (
                'id' => 79,
                'reference' => 'ALN-1453',
                'designation' => 'PARASOL ENROULABLE',
                'slug' => 'aln-1453-parasol-enroulable',
                'type_composant_id' => 1,
                'gamme_id' => NULL,
                'matiere' => NULL,
                'longueur_barre_mm' => NULL,
                'section_largeur_mm' => NULL,
                'section_hauteur_mm' => NULL,
                'epaisseur_paroi_mm' => NULL,
                'poids_lineaire_kg_m' => '1.040',
                'poids_lineaire_lbs_ft' => '0.699',
                'moment_inertie_cm4' => '12.265',
                'perimetre_mm' => '311.52',
                'image_coupe' => NULL,
                'est_disponible' => 1,
                'created_at' => '2026-09-21 16:52:46',
                'updated_at' => '2026-09-21 16:52:46',
            ),
            68 => 
            array (
                'id' => 80,
                'reference' => 'ALN-1454',
                'designation' => 'PARASOL ENROULABLE',
                'slug' => 'aln-1454-parasol-enroulable',
                'type_composant_id' => 1,
                'gamme_id' => NULL,
                'matiere' => NULL,
                'longueur_barre_mm' => NULL,
                'section_largeur_mm' => NULL,
                'section_hauteur_mm' => NULL,
                'epaisseur_paroi_mm' => NULL,
                'poids_lineaire_kg_m' => '1.432',
                'poids_lineaire_lbs_ft' => '0.962',
                'moment_inertie_cm4' => '10.725',
                'perimetre_mm' => '272.42',
                'image_coupe' => NULL,
                'est_disponible' => 1,
                'created_at' => '2026-09-21 16:55:44',
                'updated_at' => '2026-09-21 16:56:15',
            ),
            69 => 
            array (
                'id' => 81,
                'reference' => 'ALN-1455',
                'designation' => 'PARASOL ENROULABLE',
                'slug' => 'aln-1455-parasol-enroulable',
                'type_composant_id' => 1,
                'gamme_id' => NULL,
                'matiere' => NULL,
                'longueur_barre_mm' => NULL,
                'section_largeur_mm' => NULL,
                'section_hauteur_mm' => NULL,
                'epaisseur_paroi_mm' => NULL,
                'poids_lineaire_kg_m' => '0.366',
                'poids_lineaire_lbs_ft' => '0.246',
                'moment_inertie_cm4' => '4.261',
                'perimetre_mm' => '108.24',
                'image_coupe' => NULL,
                'est_disponible' => 1,
                'created_at' => '2026-09-21 16:58:11',
                'updated_at' => '2026-09-21 16:58:11',
            ),
            70 => 
            array (
                'id' => 82,
                'reference' => 'ALN-1495',
                'designation' => 'PARASOL ENROULABLE',
                'slug' => 'aln-1495-parasol-enroulable',
                'type_composant_id' => 1,
                'gamme_id' => NULL,
                'matiere' => NULL,
                'longueur_barre_mm' => NULL,
                'section_largeur_mm' => NULL,
                'section_hauteur_mm' => NULL,
                'epaisseur_paroi_mm' => NULL,
                'poids_lineaire_kg_m' => '0.853',
                'poids_lineaire_lbs_ft' => '0.573',
                'moment_inertie_cm4' => '15.365',
                'perimetre_mm' => '415.68',
                'image_coupe' => NULL,
                'est_disponible' => 1,
                'created_at' => '2026-09-21 17:03:14',
                'updated_at' => '2026-09-21 17:03:35',
            ),
            71 => 
            array (
                'id' => 83,
                'reference' => 'ALN-1576',
                'designation' => 'PARASOL ENROULABLE',
                'slug' => 'aln-1576-parasol-enroulable',
                'type_composant_id' => 1,
                'gamme_id' => NULL,
                'matiere' => NULL,
                'longueur_barre_mm' => NULL,
                'section_largeur_mm' => NULL,
                'section_hauteur_mm' => NULL,
                'epaisseur_paroi_mm' => NULL,
                'poids_lineaire_kg_m' => '1.026',
                'poids_lineaire_lbs_ft' => '0.689',
                'moment_inertie_cm4' => '7.703',
                'perimetre_mm' => '195.65',
                'image_coupe' => NULL,
                'est_disponible' => 1,
                'created_at' => '2026-09-21 17:05:19',
                'updated_at' => '2026-09-21 17:05:19',
            ),
            72 => 
            array (
                'id' => 84,
                'reference' => 'ALN-1577',
                'designation' => 'PARASOL ENROULABLE',
                'slug' => 'aln-1577-parasol-enroulable',
                'type_composant_id' => 1,
                'gamme_id' => NULL,
                'matiere' => NULL,
                'longueur_barre_mm' => NULL,
                'section_largeur_mm' => NULL,
                'section_hauteur_mm' => NULL,
                'epaisseur_paroi_mm' => NULL,
                'poids_lineaire_kg_m' => '1.319',
                'poids_lineaire_lbs_ft' => '0.886',
                'moment_inertie_cm4' => '9.826',
                'perimetre_mm' => '249.57',
                'image_coupe' => NULL,
                'est_disponible' => 1,
                'created_at' => '2026-09-21 17:08:52',
                'updated_at' => '2026-09-21 17:08:52',
            ),
            73 => 
            array (
                'id' => 85,
                'reference' => 'ALN-1570',
                'designation' => 'BARANDAS DE PISCINAS',
                'slug' => 'aln-1570-barandas-de-piscinas',
                'type_composant_id' => 1,
                'gamme_id' => NULL,
                'matiere' => NULL,
                'longueur_barre_mm' => NULL,
                'section_largeur_mm' => NULL,
                'section_hauteur_mm' => NULL,
                'epaisseur_paroi_mm' => NULL,
                'poids_lineaire_kg_m' => '0.671',
                'poids_lineaire_lbs_ft' => '0.451',
                'moment_inertie_cm4' => '11.567',
                'perimetre_mm' => '293.80',
                'image_coupe' => NULL,
                'est_disponible' => 1,
                'created_at' => '2026-09-21 19:40:03',
                'updated_at' => '2026-09-21 19:40:03',
            ),
            74 => 
            array (
                'id' => 86,
                'reference' => 'ALN-1580',
                'designation' => 'BARANDAS DE PISCINAS',
                'slug' => 'aln-1580-barandas-de-piscinas',
                'type_composant_id' => 1,
                'gamme_id' => NULL,
                'matiere' => NULL,
                'longueur_barre_mm' => NULL,
                'section_largeur_mm' => NULL,
                'section_hauteur_mm' => NULL,
                'epaisseur_paroi_mm' => NULL,
                'poids_lineaire_kg_m' => '0.168',
                'poids_lineaire_lbs_ft' => '0.113',
                'moment_inertie_cm4' => '1.962',
                'perimetre_mm' => '49.84',
                'image_coupe' => NULL,
                'est_disponible' => 1,
                'created_at' => '2026-09-21 19:41:25',
                'updated_at' => '2026-09-21 19:41:25',
            ),
            75 => 
            array (
                'id' => 87,
                'reference' => 'P-136',
                'designation' => 'BARANDAS DE PISCINAS',
                'slug' => 'p-136-barandas-de-piscinas',
                'type_composant_id' => 1,
                'gamme_id' => NULL,
                'matiere' => NULL,
                'longueur_barre_mm' => NULL,
                'section_largeur_mm' => NULL,
                'section_hauteur_mm' => NULL,
                'epaisseur_paroi_mm' => NULL,
                'poids_lineaire_kg_m' => '0.180',
                'poids_lineaire_lbs_ft' => '0.121',
                'moment_inertie_cm4' => '2.012',
                'perimetre_mm' => '51.11',
                'image_coupe' => NULL,
                'est_disponible' => 1,
                'created_at' => '2026-09-21 19:41:58',
                'updated_at' => '2026-09-21 19:41:58',
            ),
            76 => 
            array (
                'id' => 88,
                'reference' => 'ALN-1581',
                'designation' => 'BARANDAS DE PISCINAS',
                'slug' => 'aln-1581-barandas-de-piscinas',
                'type_composant_id' => 1,
                'gamme_id' => NULL,
                'matiere' => NULL,
                'longueur_barre_mm' => NULL,
                'section_largeur_mm' => NULL,
                'section_hauteur_mm' => NULL,
                'epaisseur_paroi_mm' => NULL,
                'poids_lineaire_kg_m' => '0.348',
                'poids_lineaire_lbs_ft' => '0.234',
                'moment_inertie_cm4' => '2.772',
                'perimetre_mm' => '70.42',
                'image_coupe' => NULL,
                'est_disponible' => 1,
                'created_at' => '2026-09-21 19:42:48',
                'updated_at' => '2026-09-21 19:42:48',
            ),
            77 => 
            array (
                'id' => 89,
                'reference' => 'STOA071',
                'designation' => 'BARREAU OVAL',
                'slug' => 'stoa071-barreau-oval',
                'type_composant_id' => 1,
                'gamme_id' => NULL,
                'matiere' => NULL,
                'longueur_barre_mm' => NULL,
                'section_largeur_mm' => NULL,
                'section_hauteur_mm' => NULL,
                'epaisseur_paroi_mm' => NULL,
                'poids_lineaire_kg_m' => '0.418',
                'poids_lineaire_lbs_ft' => '0.281',
                'moment_inertie_cm4' => NULL,
                'perimetre_mm' => '93.30',
                'image_coupe' => NULL,
                'est_disponible' => 1,
                'created_at' => '2026-09-21 19:45:20',
                'updated_at' => '2026-09-21 19:45:20',
            ),
            78 => 
            array (
                'id' => 90,
                'reference' => 'ALN-876',
                'designation' => 'HORIZONTAL',
                'slug' => 'aln-876-horizontal-1',
                'type_composant_id' => 1,
                'gamme_id' => NULL,
                'matiere' => NULL,
                'longueur_barre_mm' => NULL,
                'section_largeur_mm' => NULL,
                'section_hauteur_mm' => NULL,
                'epaisseur_paroi_mm' => NULL,
                'poids_lineaire_kg_m' => '0.548',
                'poids_lineaire_lbs_ft' => '0.368',
                'moment_inertie_cm4' => NULL,
                'perimetre_mm' => '205.39',
                'image_coupe' => NULL,
                'est_disponible' => 1,
                'created_at' => '2026-09-21 19:46:00',
                'updated_at' => '2026-09-21 19:46:00',
            ),
            79 => 
            array (
                'id' => 91,
                'reference' => 'ALN-1463',
                'designation' => 'BARROTES PASAMANOS',
                'slug' => 'aln-1463-barrotes-pasamanos',
                'type_composant_id' => 1,
                'gamme_id' => NULL,
                'matiere' => NULL,
                'longueur_barre_mm' => NULL,
                'section_largeur_mm' => NULL,
                'section_hauteur_mm' => NULL,
                'epaisseur_paroi_mm' => NULL,
                'poids_lineaire_kg_m' => '0.504',
                'poids_lineaire_lbs_ft' => '0.339',
                'moment_inertie_cm4' => '3.888',
                'perimetre_mm' => '98.76',
                'image_coupe' => NULL,
                'est_disponible' => 1,
                'created_at' => '2026-09-21 19:48:59',
                'updated_at' => '2026-09-21 19:48:59',
            ),
            80 => 
            array (
                'id' => 92,
                'reference' => 'ALN-1563',
                'designation' => 'BARROTES PASAMANOS',
                'slug' => 'aln-1563-barrotes-pasamanos',
                'type_composant_id' => 1,
                'gamme_id' => NULL,
                'matiere' => NULL,
                'longueur_barre_mm' => NULL,
                'section_largeur_mm' => NULL,
                'section_hauteur_mm' => NULL,
                'epaisseur_paroi_mm' => NULL,
                'poids_lineaire_kg_m' => '0.413',
                'poids_lineaire_lbs_ft' => '0.278',
                'moment_inertie_cm4' => '3.463',
                'perimetre_mm' => '87.97',
                'image_coupe' => NULL,
                'est_disponible' => 1,
                'created_at' => '2026-09-21 19:49:50',
                'updated_at' => '2026-09-21 19:49:50',
            ),
            81 => 
            array (
                'id' => 94,
                'reference' => 'ALN-1573',
                'designation' => 'BARROTES PASAMANOS',
                'slug' => 'aln-1573-barrotes-pasamanos',
                'type_composant_id' => 1,
                'gamme_id' => NULL,
                'matiere' => NULL,
                'longueur_barre_mm' => NULL,
                'section_largeur_mm' => NULL,
                'section_hauteur_mm' => NULL,
                'epaisseur_paroi_mm' => NULL,
                'poids_lineaire_kg_m' => '0.528',
                'poids_lineaire_lbs_ft' => '0.355',
                'moment_inertie_cm4' => '4.328',
                'perimetre_mm' => '109.94',
                'image_coupe' => NULL,
                'est_disponible' => 1,
                'created_at' => '2026-09-21 19:51:57',
                'updated_at' => '2026-09-21 19:51:57',
            ),
            82 => 
            array (
                'id' => 95,
                'reference' => 'ALN-1574',
                'designation' => 'BARROTES PASAMANOS',
                'slug' => 'aln-1574-barrotes-pasamanos',
                'type_composant_id' => 1,
                'gamme_id' => NULL,
                'matiere' => NULL,
                'longueur_barre_mm' => NULL,
                'section_largeur_mm' => NULL,
                'section_hauteur_mm' => NULL,
                'epaisseur_paroi_mm' => NULL,
                'poids_lineaire_kg_m' => '0.475',
                'poids_lineaire_lbs_ft' => '0.319',
                'moment_inertie_cm4' => '3.900',
                'perimetre_mm' => '99.07',
                'image_coupe' => NULL,
                'est_disponible' => 1,
                'created_at' => '2026-09-21 19:53:17',
                'updated_at' => '2026-09-21 19:53:17',
            ),
            83 => 
            array (
                'id' => 96,
                'reference' => 'ALN-1575',
                'designation' => 'BARROTES PASAMANOS',
                'slug' => 'aln-1575-barrotes-pasamanos',
                'type_composant_id' => 1,
                'gamme_id' => NULL,
                'matiere' => NULL,
                'longueur_barre_mm' => NULL,
                'section_largeur_mm' => NULL,
                'section_hauteur_mm' => NULL,
                'epaisseur_paroi_mm' => NULL,
                'poids_lineaire_kg_m' => '0.440',
                'poids_lineaire_lbs_ft' => '0.296',
                'moment_inertie_cm4' => '4.327',
                'perimetre_mm' => '109.90',
                'image_coupe' => NULL,
                'est_disponible' => 1,
                'created_at' => '2026-09-21 19:54:24',
                'updated_at' => '2026-09-21 19:54:24',
            ),
        ));
        
        
    }
}