<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class MediasTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('medias')->delete();
        
        \DB::table('medias')->insert(array (
            0 => 
            array (
                'id' => 1,
                'chemin_fichier' => 'images/composants/a7863c64-874c-4b56-94ab-c019c80ef056.png',
                'thumbnail' => NULL,
                'titre' => 'image_2026-09-11_185807567.png',
                'alt_text' => NULL,
                'description' => NULL,
                'type_media' => 'schema',
                'taille_octets' => 2697,
                'mime_type' => 'image/png',
                'largeur_px' => NULL,
                'hauteur_px' => NULL,
                'est_principal' => 1,
                'created_at' => '2026-09-11 21:58:16',
                'updated_at' => '2026-09-11 21:58:16',
                'deleted_at' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'chemin_fichier' => 'images/ouvrages/8cb9b8fd-fd61-49e6-bc1b-f5492d7f5166.png',
                'thumbnail' => NULL,
                'titre' => 'image_2026-09-11_185907431.png',
                'alt_text' => NULL,
                'description' => NULL,
                'type_media' => 'schema',
                'taille_octets' => 8888,
                'mime_type' => 'image/png',
                'largeur_px' => NULL,
                'hauteur_px' => NULL,
                'est_principal' => 0,
                'created_at' => '2026-09-11 21:59:20',
                'updated_at' => '2026-09-11 21:59:27',
                'deleted_at' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'chemin_fichier' => 'images/ouvrages/7f76e7f7-a134-4ab1-aa0d-b96c37d457a1.png',
                'thumbnail' => NULL,
                'titre' => 'image_2026-09-11_185911156.png',
                'alt_text' => NULL,
                'description' => NULL,
                'type_media' => 'schema',
                'taille_octets' => 67218,
                'mime_type' => 'image/png',
                'largeur_px' => NULL,
                'hauteur_px' => NULL,
                'est_principal' => 1,
                'created_at' => '2026-09-11 21:59:20',
                'updated_at' => '2026-09-11 21:59:28',
                'deleted_at' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'chemin_fichier' => 'images/composants/fd08efa9-bad1-458e-8e8e-b5a72661beb9.png',
                'thumbnail' => NULL,
                'titre' => 'image_2026-09-14_162031092.png',
                'alt_text' => NULL,
                'description' => NULL,
                'type_media' => 'schema',
                'taille_octets' => 9773,
                'mime_type' => 'image/png',
                'largeur_px' => NULL,
                'hauteur_px' => NULL,
                'est_principal' => 1,
                'created_at' => '2026-09-14 19:20:41',
                'updated_at' => '2026-09-14 19:20:41',
                'deleted_at' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'chemin_fichier' => 'images/composants/a3063bfc-9c75-4ae7-a488-819db6cd5e1a.png',
                'thumbnail' => NULL,
                'titre' => 'image_2026-09-14_162207667.png',
                'alt_text' => NULL,
                'description' => NULL,
                'type_media' => 'schema',
                'taille_octets' => 14642,
                'mime_type' => 'image/png',
                'largeur_px' => NULL,
                'hauteur_px' => NULL,
                'est_principal' => 1,
                'created_at' => '2026-09-14 19:22:21',
                'updated_at' => '2026-09-14 19:22:21',
                'deleted_at' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'chemin_fichier' => 'images/composants/2faae26d-c60a-4bd3-af76-b0655d164192.png',
                'thumbnail' => NULL,
                'titre' => 'image_2026-09-14_162246275.png',
                'alt_text' => NULL,
                'description' => NULL,
                'type_media' => 'schema',
                'taille_octets' => 8048,
                'mime_type' => 'image/png',
                'largeur_px' => NULL,
                'hauteur_px' => NULL,
                'est_principal' => 1,
                'created_at' => '2026-09-14 19:23:21',
                'updated_at' => '2026-09-14 19:23:21',
                'deleted_at' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'chemin_fichier' => 'images/composants/c78865ee-e5b2-42cb-87cc-78f7e21429c5.png',
                'thumbnail' => NULL,
                'titre' => 'image_2026-09-14_163452638.png',
                'alt_text' => NULL,
                'description' => NULL,
                'type_media' => 'schema',
                'taille_octets' => 16877,
                'mime_type' => 'image/png',
                'largeur_px' => NULL,
                'hauteur_px' => NULL,
                'est_principal' => 1,
                'created_at' => '2026-09-14 19:35:27',
                'updated_at' => '2026-09-14 19:35:27',
                'deleted_at' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'chemin_fichier' => 'images/composants/83e1aab4-1591-41b2-8be2-f104717196ba.png',
                'thumbnail' => NULL,
                'titre' => 'image_2026-09-14_163553039.png',
                'alt_text' => NULL,
                'description' => NULL,
                'type_media' => 'schema',
                'taille_octets' => 15219,
                'mime_type' => 'image/png',
                'largeur_px' => NULL,
                'hauteur_px' => NULL,
                'est_principal' => 1,
                'created_at' => '2026-09-14 19:36:19',
                'updated_at' => '2026-09-14 19:36:19',
                'deleted_at' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'chemin_fichier' => 'images/composants/07a80234-b5f2-4268-b628-d7df2696f044.png',
                'thumbnail' => NULL,
                'titre' => 'image_2026-09-14_163642621.png',
                'alt_text' => NULL,
                'description' => NULL,
                'type_media' => 'schema',
                'taille_octets' => 3787,
                'mime_type' => 'image/png',
                'largeur_px' => NULL,
                'hauteur_px' => NULL,
                'est_principal' => 1,
                'created_at' => '2026-09-14 19:37:10',
                'updated_at' => '2026-09-14 19:37:10',
                'deleted_at' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'chemin_fichier' => 'images/composants/9f8634dc-b574-4c64-b5db-68da71d6c282.png',
                'thumbnail' => NULL,
                'titre' => 'image_2026-09-14_163801441.png',
                'alt_text' => NULL,
                'description' => NULL,
                'type_media' => 'schema',
                'taille_octets' => 12411,
                'mime_type' => 'image/png',
                'largeur_px' => NULL,
                'hauteur_px' => NULL,
                'est_principal' => 1,
                'created_at' => '2026-09-14 19:38:27',
                'updated_at' => '2026-09-14 19:38:27',
                'deleted_at' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'chemin_fichier' => 'images/composants/f97e62a0-a8c0-4658-9fd0-f32ac4073b21.png',
                'thumbnail' => NULL,
                'titre' => 'image_2026-09-14_163851035.png',
                'alt_text' => NULL,
                'description' => NULL,
                'type_media' => 'schema',
                'taille_octets' => 6972,
                'mime_type' => 'image/png',
                'largeur_px' => NULL,
                'hauteur_px' => NULL,
                'est_principal' => 1,
                'created_at' => '2026-09-14 19:39:07',
                'updated_at' => '2026-09-14 19:39:07',
                'deleted_at' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'chemin_fichier' => 'images/composants/88fc1ce3-0fde-4a14-89f8-9381211a3551.png',
                'thumbnail' => NULL,
                'titre' => 'image_2026-09-14_163924673.png',
                'alt_text' => NULL,
                'description' => NULL,
                'type_media' => 'schema',
                'taille_octets' => 13215,
                'mime_type' => 'image/png',
                'largeur_px' => NULL,
                'hauteur_px' => NULL,
                'est_principal' => 1,
                'created_at' => '2026-09-14 19:39:48',
                'updated_at' => '2026-09-14 19:39:48',
                'deleted_at' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'chemin_fichier' => 'images/composants/6964daaa-819b-4bd8-a90b-32cfd08453c4.png',
                'thumbnail' => NULL,
                'titre' => 'image_2026-09-14_164008903.png',
                'alt_text' => NULL,
                'description' => NULL,
                'type_media' => 'schema',
                'taille_octets' => 14026,
                'mime_type' => 'image/png',
                'largeur_px' => NULL,
                'hauteur_px' => NULL,
                'est_principal' => 1,
                'created_at' => '2026-09-14 19:40:41',
                'updated_at' => '2026-09-14 19:40:41',
                'deleted_at' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'chemin_fichier' => 'images/composants/9adb1b70-4ec4-4f61-9f8e-d64570c746ef.png',
                'thumbnail' => NULL,
                'titre' => 'image_2026-09-14_164058863.png',
                'alt_text' => NULL,
                'description' => NULL,
                'type_media' => 'schema',
                'taille_octets' => 18636,
                'mime_type' => 'image/png',
                'largeur_px' => NULL,
                'hauteur_px' => NULL,
                'est_principal' => 1,
                'created_at' => '2026-09-14 19:41:20',
                'updated_at' => '2026-09-14 19:41:20',
                'deleted_at' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'chemin_fichier' => 'images/composants/6c68f2fc-9cc9-4027-9f0c-839f757fdfa3.png',
                'thumbnail' => NULL,
                'titre' => 'image_2026-09-14_164135414.png',
                'alt_text' => NULL,
                'description' => NULL,
                'type_media' => 'schema',
                'taille_octets' => 16518,
                'mime_type' => 'image/png',
                'largeur_px' => NULL,
                'hauteur_px' => NULL,
                'est_principal' => 1,
                'created_at' => '2026-09-14 19:41:52',
                'updated_at' => '2026-09-14 19:41:52',
                'deleted_at' => NULL,
            ),
        ));
        
        
    }
}