<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class MediasTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('medias')->delete();
        
        \DB::table('medias')->insert(array (
            0 => 
            array (
                'id' => 1,
                'chemin_fichier' => 'images/composants/a7863c64-874c-4b56-94ab-c019c80ef056.png',
                'thumbnail' => NULL,
                'titre' => 'image_2026-09-11_185807567.png',
                'alt_text' => NULL,
                'description' => NULL,
                'type_media' => 'schema',
                'taille_octets' => 2697,
                'mime_type' => 'image/png',
                'largeur_px' => NULL,
                'hauteur_px' => NULL,
                'est_principal' => 1,
                'created_at' => '2026-09-11 21:58:16',
                'updated_at' => '2026-09-11 21:58:16',
                'deleted_at' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'chemin_fichier' => 'images/ouvrages/8cb9b8fd-fd61-49e6-bc1b-f5492d7f5166.png',
                'thumbnail' => NULL,
                'titre' => 'image_2026-09-11_185907431.png',
                'alt_text' => NULL,
                'description' => NULL,
                'type_media' => 'schema',
                'taille_octets' => 8888,
                'mime_type' => 'image/png',
                'largeur_px' => NULL,
                'hauteur_px' => NULL,
                'est_principal' => 0,
                'created_at' => '2026-09-11 21:59:20',
                'updated_at' => '2026-09-11 21:59:27',
                'deleted_at' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'chemin_fichier' => 'images/ouvrages/7f76e7f7-a134-4ab1-aa0d-b96c37d457a1.png',
                'thumbnail' => NULL,
                'titre' => 'image_2026-09-11_185911156.png',
                'alt_text' => NULL,
                'description' => NULL,
                'type_media' => 'schema',
                'taille_octets' => 67218,
                'mime_type' => 'image/png',
                'largeur_px' => NULL,
                'hauteur_px' => NULL,
                'est_principal' => 1,
                'created_at' => '2026-09-11 21:59:20',
                'updated_at' => '2026-09-11 21:59:28',
                'deleted_at' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'chemin_fichier' => 'images/composants/fd08efa9-bad1-458e-8e8e-b5a72661beb9.png',
                'thumbnail' => NULL,
                'titre' => 'image_2026-09-14_162031092.png',
                'alt_text' => NULL,
                'description' => NULL,
                'type_media' => 'schema',
                'taille_octets' => 9773,
                'mime_type' => 'image/png',
                'largeur_px' => NULL,
                'hauteur_px' => NULL,
                'est_principal' => 1,
                'created_at' => '2026-09-14 19:20:41',
                'updated_at' => '2026-09-14 19:20:41',
                'deleted_at' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'chemin_fichier' => 'images/composants/a3063bfc-9c75-4ae7-a488-819db6cd5e1a.png',
                'thumbnail' => NULL,
                'titre' => 'image_2026-09-14_162207667.png',
                'alt_text' => NULL,
                'description' => NULL,
                'type_media' => 'schema',
                'taille_octets' => 14642,
                'mime_type' => 'image/png',
                'largeur_px' => NULL,
                'hauteur_px' => NULL,
                'est_principal' => 1,
                'created_at' => '2026-09-14 19:22:21',
                'updated_at' => '2026-09-14 19:22:21',
                'deleted_at' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'chemin_fichier' => 'images/composants/2faae26d-c60a-4bd3-af76-b0655d164192.png',
                'thumbnail' => NULL,
                'titre' => 'image_2026-09-14_162246275.png',
                'alt_text' => NULL,
                'description' => NULL,
                'type_media' => 'schema',
                'taille_octets' => 8048,
                'mime_type' => 'image/png',
                'largeur_px' => NULL,
                'hauteur_px' => NULL,
                'est_principal' => 1,
                'created_at' => '2026-09-14 19:23:21',
                'updated_at' => '2026-09-14 19:23:21',
                'deleted_at' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'chemin_fichier' => 'images/composants/c78865ee-e5b2-42cb-87cc-78f7e21429c5.png',
                'thumbnail' => NULL,
                'titre' => 'image_2026-09-14_163452638.png',
                'alt_text' => NULL,
                'description' => NULL,
                'type_media' => 'schema',
                'taille_octets' => 16877,
                'mime_type' => 'image/png',
                'largeur_px' => NULL,
                'hauteur_px' => NULL,
                'est_principal' => 1,
                'created_at' => '2026-09-14 19:35:27',
                'updated_at' => '2026-09-14 19:35:27',
                'deleted_at' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'chemin_fichier' => 'images/composants/83e1aab4-1591-41b2-8be2-f104717196ba.png',
                'thumbnail' => NULL,
                'titre' => 'image_2026-09-14_163553039.png',
                'alt_text' => NULL,
                'description' => NULL,
                'type_media' => 'schema',
                'taille_octets' => 15219,
                'mime_type' => 'image/png',
                'largeur_px' => NULL,
                'hauteur_px' => NULL,
                'est_principal' => 1,
                'created_at' => '2026-09-14 19:36:19',
                'updated_at' => '2026-09-14 19:36:19',
                'deleted_at' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'chemin_fichier' => 'images/composants/07a80234-b5f2-4268-b628-d7df2696f044.png',
                'thumbnail' => NULL,
                'titre' => 'image_2026-09-14_163642621.png',
                'alt_text' => NULL,
                'description' => NULL,
                'type_media' => 'schema',
                'taille_octets' => 3787,
                'mime_type' => 'image/png',
                'largeur_px' => NULL,
                'hauteur_px' => NULL,
                'est_principal' => 1,
                'created_at' => '2026-09-14 19:37:10',
                'updated_at' => '2026-09-14 19:37:10',
                'deleted_at' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'chemin_fichier' => 'images/composants/9f8634dc-b574-4c64-b5db-68da71d6c282.png',
                'thumbnail' => NULL,
                'titre' => 'image_2026-09-14_163801441.png',
                'alt_text' => NULL,
                'description' => NULL,
                'type_media' => 'schema',
                'taille_octets' => 12411,
                'mime_type' => 'image/png',
                'largeur_px' => NULL,
                'hauteur_px' => NULL,
                'est_principal' => 1,
                'created_at' => '2026-09-14 19:38:27',
                'updated_at' => '2026-09-14 19:38:27',
                'deleted_at' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'chemin_fichier' => 'images/composants/f97e62a0-a8c0-4658-9fd0-f32ac4073b21.png',
                'thumbnail' => NULL,
                'titre' => 'image_2026-09-14_163851035.png',
                'alt_text' => NULL,
                'description' => NULL,
                'type_media' => 'schema',
                'taille_octets' => 6972,
                'mime_type' => 'image/png',
                'largeur_px' => NULL,
                'hauteur_px' => NULL,
                'est_principal' => 1,
                'created_at' => '2026-09-14 19:39:07',
                'updated_at' => '2026-09-14 19:39:07',
                'deleted_at' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'chemin_fichier' => 'images/composants/88fc1ce3-0fde-4a14-89f8-9381211a3551.png',
                'thumbnail' => NULL,
                'titre' => 'image_2026-09-14_163924673.png',
                'alt_text' => NULL,
                'description' => NULL,
                'type_media' => 'schema',
                'taille_octets' => 13215,
                'mime_type' => 'image/png',
                'largeur_px' => NULL,
                'hauteur_px' => NULL,
                'est_principal' => 1,
                'created_at' => '2026-09-14 19:39:48',
                'updated_at' => '2026-09-14 19:39:48',
                'deleted_at' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'chemin_fichier' => 'images/composants/6964daaa-819b-4bd8-a90b-32cfd08453c4.png',
                'thumbnail' => NULL,
                'titre' => 'image_2026-09-14_164008903.png',
                'alt_text' => NULL,
                'description' => NULL,
                'type_media' => 'schema',
                'taille_octets' => 14026,
                'mime_type' => 'image/png',
                'largeur_px' => NULL,
                'hauteur_px' => NULL,
                'est_principal' => 1,
                'created_at' => '2026-09-14 19:40:41',
                'updated_at' => '2026-09-14 19:40:41',
                'deleted_at' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'chemin_fichier' => 'images/composants/9adb1b70-4ec4-4f61-9f8e-d64570c746ef.png',
                'thumbnail' => NULL,
                'titre' => 'image_2026-09-14_164058863.png',
                'alt_text' => NULL,
                'description' => NULL,
                'type_media' => 'schema',
                'taille_octets' => 18636,
                'mime_type' => 'image/png',
                'largeur_px' => NULL,
                'hauteur_px' => NULL,
                'est_principal' => 1,
                'created_at' => '2026-09-14 19:41:20',
                'updated_at' => '2026-09-14 19:41:20',
                'deleted_at' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'chemin_fichier' => 'images/composants/6c68f2fc-9cc9-4027-9f0c-839f757fdfa3.png',
                'thumbnail' => NULL,
                'titre' => 'image_2026-09-14_164135414.png',
                'alt_text' => NULL,
                'description' => NULL,
                'type_media' => 'schema',
                'taille_octets' => 16518,
                'mime_type' => 'image/png',
                'largeur_px' => NULL,
                'hauteur_px' => NULL,
                'est_principal' => 1,
                'created_at' => '2026-09-14 19:41:52',
                'updated_at' => '2026-09-14 19:41:52',
                'deleted_at' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'chemin_fichier' => 'images/composants/eae2a6ae-af15-4b4d-8e0a-958614fc761f.png',
                'thumbnail' => NULL,
                'titre' => 'image_2026-09-15_153710892.png',
                'alt_text' => NULL,
                'description' => NULL,
                'type_media' => 'schema',
                'taille_octets' => 30728,
                'mime_type' => 'image/png',
                'largeur_px' => NULL,
                'hauteur_px' => NULL,
                'est_principal' => 1,
                'created_at' => '2026-09-15 18:37:39',
                'updated_at' => '2026-09-15 18:37:39',
                'deleted_at' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                'chemin_fichier' => 'images/composants/b2dad163-41a8-4aa0-8e9e-14f980e315ac.png',
                'thumbnail' => NULL,
                'titre' => 'image_2026-09-15_155347515.png',
                'alt_text' => NULL,
                'description' => NULL,
                'type_media' => 'schema',
                'taille_octets' => 23186,
                'mime_type' => 'image/png',
                'largeur_px' => NULL,
                'hauteur_px' => NULL,
                'est_principal' => 1,
                'created_at' => '2026-09-15 18:53:49',
                'updated_at' => '2026-09-15 18:53:49',
                'deleted_at' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'chemin_fichier' => 'images/composants/66d36fe5-784a-47b4-bdeb-3236eac78942.png',
                'thumbnail' => NULL,
                'titre' => 'image_2026-09-15_155514453.png',
                'alt_text' => NULL,
                'description' => NULL,
                'type_media' => 'schema',
                'taille_octets' => 35505,
                'mime_type' => 'image/png',
                'largeur_px' => NULL,
                'hauteur_px' => NULL,
                'est_principal' => 1,
                'created_at' => '2026-09-15 18:55:41',
                'updated_at' => '2026-09-15 18:55:41',
                'deleted_at' => NULL,
            ),
            18 => 
            array (
                'id' => 19,
                'chemin_fichier' => 'images/composants/b79969ed-3d7b-430f-8d55-0d86e6177da2.png',
                'thumbnail' => NULL,
                'titre' => 'image_2026-09-15_155649750.png',
                'alt_text' => NULL,
                'description' => NULL,
                'type_media' => 'schema',
                'taille_octets' => 12105,
                'mime_type' => 'image/png',
                'largeur_px' => NULL,
                'hauteur_px' => NULL,
                'est_principal' => 1,
                'created_at' => '2026-09-15 18:57:33',
                'updated_at' => '2026-09-15 18:57:33',
                'deleted_at' => NULL,
            ),
            19 => 
            array (
                'id' => 20,
                'chemin_fichier' => 'images/composants/d15d88ae-f588-4edc-84dc-6ad93731be20.png',
                'thumbnail' => NULL,
                'titre' => 'image_2026-09-15_155854402.png',
                'alt_text' => NULL,
                'description' => NULL,
                'type_media' => 'schema',
                'taille_octets' => 56916,
                'mime_type' => 'image/png',
                'largeur_px' => NULL,
                'hauteur_px' => NULL,
                'est_principal' => 1,
                'created_at' => '2026-09-15 18:59:22',
                'updated_at' => '2026-09-15 18:59:22',
                'deleted_at' => NULL,
            ),
            20 => 
            array (
                'id' => 21,
                'chemin_fichier' => 'images/composants/6ca43975-849a-4b58-9cb1-4418f492d020.png',
                'thumbnail' => NULL,
                'titre' => 'image_2026-09-15_155938724.png',
                'alt_text' => NULL,
                'description' => NULL,
                'type_media' => 'schema',
                'taille_octets' => 6431,
                'mime_type' => 'image/png',
                'largeur_px' => NULL,
                'hauteur_px' => NULL,
                'est_principal' => 1,
                'created_at' => '2026-09-15 19:00:10',
                'updated_at' => '2026-09-15 19:00:10',
                'deleted_at' => NULL,
            ),
            21 => 
            array (
                'id' => 22,
                'chemin_fichier' => 'images/composants/01ae0fc7-f231-42b9-b4cb-14355ef26dae.png',
                'thumbnail' => NULL,
                'titre' => 'image_2026-09-15_160026822.png',
                'alt_text' => NULL,
                'description' => NULL,
                'type_media' => 'schema',
                'taille_octets' => 10577,
                'mime_type' => 'image/png',
                'largeur_px' => NULL,
                'hauteur_px' => NULL,
                'est_principal' => 1,
                'created_at' => '2026-09-15 19:01:05',
                'updated_at' => '2026-09-15 19:01:05',
                'deleted_at' => NULL,
            ),
            22 => 
            array (
                'id' => 23,
                'chemin_fichier' => 'images/composants/e564f349-7ffa-4aeb-8597-4eb2e196d16a.png',
                'thumbnail' => NULL,
                'titre' => 'image_2026-09-15_160131628.png',
                'alt_text' => NULL,
                'description' => NULL,
                'type_media' => 'schema',
                'taille_octets' => 7163,
                'mime_type' => 'image/png',
                'largeur_px' => NULL,
                'hauteur_px' => NULL,
                'est_principal' => 1,
                'created_at' => '2026-09-15 19:01:58',
                'updated_at' => '2026-09-15 19:01:58',
                'deleted_at' => NULL,
            ),
            23 => 
            array (
                'id' => 24,
                'chemin_fichier' => 'images/composants/37e336f5-3ebe-4ff7-b8aa-3383b5289457.png',
                'thumbnail' => NULL,
                'titre' => 'image_2026-09-15_160224967.png',
                'alt_text' => NULL,
                'description' => NULL,
                'type_media' => 'schema',
                'taille_octets' => 15998,
                'mime_type' => 'image/png',
                'largeur_px' => NULL,
                'hauteur_px' => NULL,
                'est_principal' => 1,
                'created_at' => '2026-09-15 19:02:53',
                'updated_at' => '2026-09-15 19:02:53',
                'deleted_at' => NULL,
            ),
            24 => 
            array (
                'id' => 25,
                'chemin_fichier' => 'images/ouvrages/06dfb9c0-beec-4019-bf9a-561259a86f35.png',
                'thumbnail' => NULL,
                'titre' => 'image_2026-09-15_160527626.png',
                'alt_text' => NULL,
                'description' => NULL,
                'type_media' => 'schema',
                'taille_octets' => 62950,
                'mime_type' => 'image/png',
                'largeur_px' => NULL,
                'hauteur_px' => NULL,
                'est_principal' => 1,
                'created_at' => '2026-09-15 19:06:18',
                'updated_at' => '2026-09-15 19:06:18',
                'deleted_at' => NULL,
            ),
        ));
        
        
    }
}